- cmd/konvoy-image-wrapper/cmd/wrapper.go
Set the ssh config file permissions to `0600` in the event that the
environment's `umask` allows group or other write permissions by
default.
> wrapper: force ssh config file permissions

- cmd/konvoy-image/cmd/build.go
- cmd/konvoy-image/cmd/generate.go
The `generate` command was ignoring `overrides` CLI flag.
```
./bin/konvoy-images generate [path] --overrides [override-path]
```
> fix: override flags not passed on generate command

- .github/workflows/lint.yml
- .gitignore
- .golangci.yml
- Makefile
- cmd/konvoy-image-wrapper/cmd/wrapper.go
- hack/fetch-flatcar-ami.sh
- hack/flatcar-ami.pkr.hcl
- hack/setup_environment.py
- images/ami/flatcar.yaml
- packer/files/no-update-flatcar.sh
- pkg/app/build.go
- pkg/packer/manifests/aws/packer.json.tmpl
To ensure the Nvidia driver continues to work, we need to be conservative with kernel upgrades. Flatcar in particular upgrades automatically. Disable upgrades (and their reboots) on Flatcar to provide a similar model to other OS's.
Since the OS does not upgrade, encode the OS version in the AMI name. This requires retrieval of the AMI data before running the AMI build. This is done by running a small HCL build (in `hack/flatcar-ami.pkr.hcl`) that fetches the latest Flatcar AMI and creates an override file to set the `distribution_version`.
https://jira.d2iq.com/browse/D2IQ-76956
> Disable automatic updates for Flatcar

- ansible/group_vars/all/defaults.yaml
- ansible/roles/images/defaults/main.yaml
- images/ami/flatcar.yaml
- images/common.yaml
Fixes https://jira.d2iq.com/browse/D2IQ-77290
- Kubernetes `v1.21.3` and bumped pause and coredns image versions
- Containerd `v1.4.7`
Verified locally
```
==> Wait completed after 10 minutes 28 seconds
==> Builds finished. The artifacts of successful builds are:
--> centos-7: AMIs were created:
us-west-2: ami-0b5f91ff66c0d5bb7
--> centos-7: AMIs were created:
us-west-2: ami-0b5f91ff66c0d5bb7
```
```
[root@ip-172-31-25-100 centos]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:03:28Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
[root@ip-172-31-25-100 centos]# kubelet --version
Kubernetes v1.21.3
[root@ip-172-31-25-100 centos]# …
```
> feat: version bumps

- ansible/molecule/ec2_full/molecule.yml
- ansible/roles/packages/tasks/install-redhat.yaml
- ansible/roles/sysprep/tasks/redhat.yml
Image builder, which this tool is based off of states that we need subscription manager to build rhel images. This PR removes that dependency by using the public key and repository directly. 
RHEL 8 GPG key bits taken from here https://github.com/ansible/ansible/issues/71634#issuecomment-687229416
> fix: remove refs to subscription manager

- images/ami/flatcar.yaml
I was able to get p2 and m5 instances to boot with the following AMI 
```
us-west-2: ami-04dda24fc991fe75a
```
```
{
"Images": [
{
"Architecture": "x86_64",
"CreationDate": "2021-08-17T21:37:40.000Z",
"ImageId": "ami-04dda24fc991fe75a",
"ImageLocation": "999867407951/konvoy-ami-flatcar-stable-1.21.3-1629235858",
"ImageType": "machine",
"Public": true,
"OwnerId": "999867407951",
"PlatformDetails": "Linux/UNIX",
"UsageOperation": "RunInstances",
"State": "available",
"BlockDeviceMappings": [
{
"DeviceName": "/dev/xvda",
"Ebs": {
"DeleteOnTermination": true,
"Iops": 3000,
"SnapshotId": "snap-00a43140346afe811",
"VolumeSize": 10,
"VolumeType": "gp3",
"Throughput": 125,
"Encrypted": false
}
},
{
"DeviceName": "/dev/xvdb",
"VirtualName": "ephemeral0"
}
],
"Description": "Konvoy base for …
```
> fix: use dev/xvda as default volume for flatcar

- cmd/konvoy-image/cmd/args.go
- pkg/app/build.go
- pkg/packer/manifests/aws/packer.json.tmpl
We need to be able to make sure that flatcar images are built on p2.xlarge instances. 
I would like to avoid the command line option and instead have this somehow based on the parameters given. Don't know how though. In this specific case, we need to enable p2.xlarge when a user selected flatcar and enabled gpu overrides.
> feat: adds instance type override option to build app

- Makefile
- ansible/vars/flatcar/flatcar.yaml
Fixes socket mixup introduced via https://github.com/mesosphere/konvoy-image-builder/commit/8cf3a5ffbeecae2a9c4ad141834007975a476fbe#diff-6cd7dde3b0707c4663c2e23028d4da79899f916586421e3364621480207aaf71
> fix: set docker containerd shim socket

- ansible/roles/packages/tasks/install-flatcar.yaml
- ansible/roles/packages/tasks/install.yaml
Upon containerd reconfiguraiton, we should restart containerd so that it picks up the new configuration. This PR restarts containerd when the config.toml is updated on RedHat based OSes.
Flatcar will require additional changes to implement this.
> fix: restart containerd upon reconfig

- .dockerignore
- .github/workflows/goreleaser.yml
- .goreleaser.yml
- Dockerfile
Configures the goreleaser release job to push the docker image. The `auto` option ignores pushes for pre-releases https://goreleaser.com/customization/docker_manifest/
Related JIRA: https://jira.d2iq.com/browse/D2IQ-78865
> feat: push image on release

- Makefile
Summary:
Pass the correct environment variables and volumes to the devkit container to fix the goreleaser github action.
> fix: propogate release variables to buildkit run

- .goreleaser.yml
Saw an issue when using the latest v1.1.0 version, the image tagged is `mesosphere/konvoy-image-builder:v1.1.0` but the wrapper is looking for `mesosphere/konvoy-image-builder:1.1.0`
This because its based on the `version` see [here](https://github.com/mesosphere/konvoy-image-builder/blob/ed8c4ebdb27134af905dd483545c77434e4e92f5/cmd/konvoy-image-wrapper/image/common.go#L29) and with goreleaser the version being set was without the "v".
The previous v1.0.0 had the "v" from the [Makefile](https://github.com/mesosphere/konvoy-image-builder/blob/main/Makefile#L10).
```
➜  konvoy-image-bundle-v1.1.0_darwin_amd64 ./konvoy-image --version
e2eb06d8af82: Loading layer [==================================================>]  5.865MB/5.865MB
8282b5af8ab6: Loading layer …
```
> fix: use "v" in versions

- ansible/roles/gpu/tasks/nvidia-gpu-SLES15.yaml
- ansible/roles/packages/tasks/install-suse.yaml
In two control runs we saw two failures that might be retryable:
```
TASK [gpu : Install Nvidia drivers]
[...]
Failed to provide Package libX11-data-1.6.5-3.21.1.noarch (SLE-Module-Basesystem15-SP3-Updates). Do you want to retry retrieval?
```
```
TASK [packages : install common packages]
[...]
sles-15: fatal: [default]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+audit", "+conntrack-tools", "+open-vm-tools", "+python3-pip", "+python3-netifaces", "+socat", "+sysstat", "+nfs-utils"], "msg": "Zypper run command failed with return code 1.", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "<?xml …
```
> Increased retries for SLES

- ansible/group_vars/all/defaults.yaml
- docs/cli/konvoy-image_provision.md
This only effects flatcar installations. The kubelet packages depends on a specific version of cri-tools for debian and rpm bases systems.
> bump crictl

- ansible/group_vars/all/defaults.yaml
- images/common.yaml
Bumping the default k8s version.
Also updated `crictl_version`, looks like it was missed in the previous PR?
> feat: k8s v1.21.6

- .github/workflows/goreleaser.yml
- Dockerfile.devkit
We don't need to run this on PRs, only on merges to main and when we cut tags.
> fix: don't run goreleaser on PRs

- ansible/roles/gpu/defaults/main.yaml
- ansible/roles/packages/tasks/install-redhat.yaml
- cmd/konvoy-image-wrapper/cmd/wrapper.go
- images/common.yaml
Allows the user to specify an epel source that can be different from the upstream ones. This allows the user to download packages from their own local mirror or yum repository
> chore: refactor build to use epel params

- ansible/group_vars/all/defaults.yaml
- images/common.yaml
The SHA256 came from https://github.com/containerd/containerd/releases/download/v1.4.11/containerd-1.4.11-linux-amd64.tar.gz.sha256sum
> feat: bump Containerd to 1.4.11

- pkg/app/build.go
The field is currently testing this in govcloud regions on multi-region amis. Once they sign off, we can merge.
> fix formatting of ami-regions

- ansible/roles/packages/tasks/install-redhat.yaml
There is a variable for this, but it was not being used.
> ansible: fix container-selinux gpg key

- Makefile
- ansible/molecule/ec2_full/molecule.yml
- ansible/molecule/ec2_gpu/molecule.yml
- ansible/roles/gpu/defaults/main.yaml
- ansible/roles/gpu/tasks/nvidia-gpu-RHEL7.yaml
- ansible/roles/gpu/tasks/nvidia-gpu-RHEL8.yaml
- ansible/roles/gpu/tasks/nvidia-gpu-SLES15.yaml
- ansible/roles/packages/tasks/repo-suse.yaml
- images/ami/centos-7.yaml
- images/ami/centos-8.yaml
- images/ami/oracle-7.yaml
- images/ami/rhel-79.yaml
- images/ami/rhel-82.yaml
- images/ami/rhel-84.yaml
- adds rhel82 molecule target
- renames rhel8 ami image template and build-result to rhel82 for consistency
- adds missing Makefile target for sles15
- increases retry delays for sles15 significantly to avoid rate limits
CONTROVERSIAL:
- limits rhel8.2 to a base image that has kernel headers available
- adds rhel8 support for run file driver installation
- adds rhel7 support for run file driver installation
TESTING:
All touched image variants were tested on GPU nodes using Konvoy's provisioning on AWS.
RHEL8.4 showed GPU unrelated issues which are still being debugged.
RHEL 7.9 / 470.x: konvoy-ami-rhel-7-nvidia-1.21.6-1637360496: ami-03fd6597fbe7bdb7b
RHEL 8.2 / 470.x: konvoy-ami-rhel-8-nvidia-1.21.6-1637506302: ami-09bd720906c3ba58e
RHEL 8.4 / 470.x: …
> feat: RHEL 8.4, RHEL 8.2 & RHEL 7.9 GPU support

- ansible/molecule/ec2_full/molecule.yml
The Nvidia run file installer as currently used for RHEL8.2 demands a GPU node for tests.
> fix: RHEL8.2 now needs GPU nodes for builds and tests

- ansible/roles/sysprep/tasks/main.yml
Remove swap lines from fstab during sysprep phase so provisioning physical hosts that may have it setup during the install will not fail the setup later when kubelet tries to start.
> ansible: remove swap from fstab during sysprep

- ansible/roles/gpu/files/nvidia-driver
Since the release of flatcar 5.10.82 the build for 5.10.80 is broken. @joejulian identified the problem in the nvidia prerequisites installer, this is the fix. 
The original version was targeting the kernel sources in a way that would occasionally work, but definitely not reliably.
Tested directly in molecule ec2_full run;
```
$ uname -r
5.10.80-flatcar
$ sudo nvidia-smi
Wed Dec  1 23:21:25 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. | …
```
> fix: flatcar gpu build fix for kernel 5.10.80.

- ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
Without this change the nvidia-container-runtime will fail isolating the GPU devices as it is not CGroups V2 compatible. Flatcar switched to CGroups V2 by default a while ago.
Without the change, the runtime will barf like this:
```
sudo ctr -a /run/docker/libcontainerd/docker-containerd.sock run --rm --gpus 0 -t docker.io/nvidia/cuda:11.0-base cuda-11.0-base nvidia-smi
ctr: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: container error: cgroup subsystem devices not found: unknown
```
Testing this change on a molecule test node:
```
$ sudo ctr -a …
```
> fix: prevents use of cgroupsv2 for flatcar gpu

- ansible/roles/gpu/files/daemon.json
- ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
Just for having a neatly setup system for users trying to run GPU workload on the CLI for some reason. Without this patch, one can not use the docker cli for GPU workload on container level (but only `ctr`).
Tested: 
```
$ docker run --runtime=nvidia --rm nvidia/cuda:11.0-base nvidia-smi
Sun Dec  5 23:54:00 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. | …
```
> fix: allows for selecting nvidia runtime via docker cli

- ansible/roles/images/tasks/main.yaml
Fixes https://jira.d2iq.com/browse/D2IQ-82054
The default configuration for the `containerd` disables the `cri`
plugin. Since debian distros start services on install, we need to make
sure to `restart` containerd prior to pulling the images so it is using
our generated config.
> ansible: fix ubuntu-18 build

- ansible/roles/networking/tasks/main.yaml
- ansible/roles/sysprep/tasks/main.yml
Allows the user to disable firewalld as a last step in system prep. The default will be to keep firewalld running. 
JIRAs: 
- https://jira.d2iq.com/browse/D2IQ-82085
- https://jira.d2iq.com/browse/D2IQ-82086
- https://jira.d2iq.com/browse/D2IQ-82087
> feat: disable firewalld and flush Iptable rules

- Makefile
Make it possible to use ssh keys in the devkit container. I wasn't able to run kib without this on my Linux machine. Was it user error? Feedback welcome.
```release-note
```
> Make ssh-agent available in the devkit container

- ansible/roles/images/defaults/main.yaml
The images in konvoy's image bundle have [canonical](https://pkg.go.dev/github.com/docker/distribution/reference#Canonical) names (ok, they don't have their digest in the name, so I guess they're not technically canonical...) 
In this case, kib used a _different_ name, without a fully-qualified registry, i.e., `mesosphere/kfips` instead of `docker.io/mesosphere/kfips`. Because the name is different, kib cannot find the image, although it is present.
**I think there's more to discuss here. Let's consider whether image names can/do/should change when users source them from private registries (or mirrors).**
**Does this PR introduce a …
> Use canonical name for mesosphere/kfips image

- ansible/roles/networking/tasks/main.yaml
Flatcar has a bad iptables service and fails with this error when disabling it 
```
Error loading unit file 'iptables': org.freedesktop.systemd1.BadUnitSetting
```
This prevents the tasks for flatcar from running at all. We know we will be safe because we have not run into these issues on flatcar before #156 was introduced.
```release-note
Removes iptables service tasks from running on flatcar 
```
>  fix: adds more conditions for iptables service

- ansible/roles/networking/tasks/main.yaml
- hack/flatcar-ami.pkr.hcl
e2e failures https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_E2e/3309292?buildTab=log&focusLine=15382&linesState=389
```release-note
```
> fix: always select x86_64 arch for Flatcar

- .goreleaser.yml
skip_auto is set to true preventing the push of rc images.
```release-note
```
> publish rcs

- .goreleaser.yml
No longer build excess v{major}.{minor} tags and v{major} tags as we push rc to dockerhub as well now.
```release-note
```
> build: stop building tags that aren't a part of the current release

- Dockerfile
Reverts mesosphere/konvoy-image-builder#148 to fix this issue https://githubmemory.com/repo/atmoz/sftp/issues/296
It appears that the keys packer is creating are not compatible with this new version of open-ssh (8.8) that is shipped with alpine. This is a quick measure until we can figure out how to get packer to create different key types that are compatible with open-ssh 8.8
> Revert "build(deps): bump alpine from 3.14.2 to 3.15.0"

- ansible/roles/sysprep/tasks/redhat.yml
- ansible/roles/sysprep/tasks/suse.yml
fix error when swap is on and the systemd service `temp-disk-swapfile` doesn't exist
```release-note
```
> only manage a systemd service if it exists

- .github/super-linter.env
- .github/workflows/golangci-lint.yml
- .golangci.yml
This also disables golang linting in super-linter due to a design flaw
in super-linter.
> build(lint): switch from golint to revive

- Makefile
Starting the implementation of https://docs.google.com/document/d/1z8tKXa-9oA7PVGEN5TrXJLS5MAq_GkYHsB6tdyFWySc/edit?usp=sharing
This PR will enable us to setup CI jobs that will run on KIB tags to build AMIs with unique names, something like:
```
konvoy-ami-centos-7-1.21.6-release-1638930659
```
This will then allow to use `--ami-format` when creating AWS e2e clusters with latest KIB releases.
```release-note
```
> chore: remove duplicate Makefile code and add overrides

- Makefile
- pkg/app/build.go
Sets the correct KIB version in the ami tag. Previously this was always defaulting to `0.0.1` from the fallback value in `pkg/packer/manifests/aws/packer.json.tmpl`.
```release-note
Fix: The correct Konvoy Image Builder version will be set in the resulting AMI tags.
```
> fix: set the correct KIB version ami tag

- ansible/roles/config/templates/config.toml.tmpl
Allows user to provide a subset of registry configuration fields.
* https://jira.d2iq.com/browse/D2IQ-83441
Any suggestions on where to test this?
```release-note
The user can omit unused fields from their registry credentials override.
```
> fix: Allow user to provide a subset of registry configuration fields

- Makefile
- ansible/roles/packages/tasks/install-redhat.yaml
- hack/os-packages/Makefile
- hack/os-packages/rpm-artifacts-getter-7/Dockerfile
- hack/os-packages/rpm-artifacts-getter/centos/7/Dockerfile
- hack/os-packages/rpm-artifacts-getter/centos/7/containerd.repo
- hack/os-packages/rpm-artifacts-getter/centos/7/kubernetes.repo
- hack/os-packages/rpm-fips-artifacts-getter/centos/7/Dockerfile
- hack/os-packages/rpm-fips-artifacts-getter/centos/7/containerd.fips.repo
- hack/os-packages/rpm-fips-artifacts-getter/centos/7/kubernetes.fips.repo
- overrides/offline-fips.yaml
- build rhel 7.9 AMI for FIPS and airgapped mode
- refactor `os-package` building code to support multiple OS distros/versions/FIPS combinations
- https://jira.d2iq.com/browse/D2IQ-83344
```release-note
```
> chore: create RHEL 7.9 fips image for airgapped installations

- .golangci.yml
- ansible/upload-artifacts.yaml
- cmd/konvoy-image/cmd/artifacts.go
- cmd/konvoy-image/cmd/root.go
- cmd/konvoy-image/cmd/upload.go
- cmd/konvoy-image/cmd/validate.go
- docs/cli/konvoy-image.md
- docs/cli/konvoy-image_upload.md
- docs/cli/konvoy-image_upload_artifacts.md
- pkg/app/artifacts.go
Creates an `upload artifacts` command to upload artifacts to hosts specified in an inventory file.
https://jira.d2iq.com/browse/D2IQ-83933
I ran the command like so:
```
$ bin/konvoy-image-wrapper upload artifacts --inventory-file=ansible-inventory.yaml --container-images-dir=./artifacts/image-bundles/ --os-packages-bundle=./artifacts/os-packages_1.21.6_x86_64_rpms.tar.gz --pip-packages-bundle=./artifacts/pip-packages.tar.gz 
```
I used previous existing terraform scripts to bring up centos7 hosts. 
```release-note
feat: adds a upload artifacts command for hosts that will be used in offline mode.
```
> feat: adds an upload artifacts command to konvoy image builder

- cmd/konvoy-image/cmd/args.go
- cmd/konvoy-image/cmd/generate.go
- cmd/konvoy-image/cmd/provision.go
- docs/cli/konvoy-image_build.md
- docs/cli/konvoy-image_generate.md
- docs/cli/konvoy-image_provision.md
- pkg/app/build.go
Wires the values of `extra-vars` flag to the `builder` which is used for provisioning.
Also adds `extra-vars` flag to `build` and `generate` commands
* https://jira.d2iq.com/browse/D2IQ-84265 
```release-note
fix: wires extra vars correctly 
feat: add extra-vars to build and generate commands
```
> fix: wires extra vars correctly 

- ansible/roles/gpu/tasks/nvidia-gpu-SLES15.yaml
Works around connectivity issues we see in e2e tests. Per @jkoelker:
> the issue is SLES on aws uses an aws local mirror, and yea that get rate limited. IIRC its on a per tenant (vpc egress ip is what its actually tracking), so it would limit the number of concurrent builds we have ;(. Is there a way we can serialize it in TC, so that at most there are X SLES based builds running at any given time period?
Example failure from https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_E2eSles15nvidia/3344885?showLog=3344885_1757_478.1757&logFilter=debug:
```
sles-15-nvidia: TASK [gpu : Activate PackageHub 15.3 x86_64] ***********************************
sles-15-nvidia: fatal: [default]: FAILED! => {
"changed": false,
"cmd": [ …
```
> chore: Retry more SLES tasks to work around connectivity issues

- ansible/roles/images/tasks/check-or-pull-images.yaml
Reported in Slack https://mesosphere.slack.com/archives/C01MPKVBB5E/p1646197247844029
`ctr` does not use the same Containerd mirror configuration, lets go back to using `crictl` to pull the images which will use Containerd mirrors.
This is basically the command we had before https://github.com/mesosphere/konvoy-image-builder/pull/162/files#diff-14c84fc26cc68826bdd8c9ee2ba0b29f31537fc6fec4f03028d38b024d7b9d6cL12
```release-note
```
> fix: use crictl to pull images and supports mirrors

- ansible/group_vars/all/defaults.yaml
The kfips image used in `dkp check cluster fips` is the responsibility of konvoy not KIB, removing it from here and I will open a PR in Konvoy to add it there. 
PR in Konvoy https://github.com/mesosphere/konvoy2/pull/1104
```release-note
```
> chore: remove pulling kfips image

- ansible/group_vars/all/defaults.yaml
- ansible/group_vars/all/system.yaml
- ansible/roles/repo/tasks/suse.yaml
- ansible/roles/version/tasks/main.yaml
- ansible/roles/version/templates/kubeadm-conf.yaml.tmpl
- images/common.yaml
- overrides/fips.yaml
* Bumps k8s to 1.22.4
* Removed old note (repository promotion job now exists)
* https://jira.d2iq.com/browse/D2IQ-81792
```release-note
Feature: Default to Kubernetes 1.22.7
```
> feat: bump k8s to 1.22.8

- Dockerfile
- pkg/packer/manifests/aws/packer.json.tmpl
- pkg/packer/manifests/vsphere/packer.json.tmpl
Reverts mesosphere/konvoy-image-builder#250 and goes back to a working version
@jkoelker reported the issue in https://github.com/mesosphere/konvoy-image-builder/pull/271
> Revert "chore: bump alpine to 3.15"

- Dockerfile.devkit
- pkg/packer/manifests/vsphere/packer.json.tmpl
- If `--dry-run` option is provided, destroys vsphere VM that was created during image building 
- This will automatically cleanup the VMS when a PR builds are run with `--dry-run` mode.
- After this PR, only `released` vsphere templates should remain in our vSphere cluster
Once the PR is merged I will destroy all the left over VMs that were created so far.
> fix: cleanup vsphere VM when building vSphere template in dry run

- Makefile
- fixes makefile targets that does not add `--aws-instance-type` option for NVIDIA GPU support
```release-note
```
> fix: makefile targets for NVIDIA GPU support

- Makefile
Has offline vsphere template builds use bastion to build templates, similar to normal offline configuration
```release-note
```
> fix: use bastion in offline fips ova rhel builds

- Makefile
- pkg/app/build.go
Two misc fixes I found while working on getting CI setup.
```release-note
```
> fix(azure): always ensure image definitions

- Makefile
- cmd/konvoy-image/cmd/aws.go
- cmd/konvoy-image/cmd/azure.go
- docs/cli/konvoy-image_build.md
- docs/cli/konvoy-image_build_aws.md
- docs/cli/konvoy-image_build_azure.md
- docs/cli/konvoy-image_generate.md
- docs/cli/konvoy-image_generate_aws.md
- docs/cli/konvoy-image_generate_azure.md
- images/azure/rhel-8.yaml
- make/ci.mk
- make/images.mk
- pkg/app/build.go
- pkg/app/config.go
- pkg/app/constants.go
- test/e2e/scripts/clean-last-azure-image.sh
- test/infra/aws/Makefile
- test/infra/aws/export.sh
- test/infra/vsphere/Makefile
- test/infra/vsphere/export.sh
DRY up the current build targets by using `pattern` targets.
The basis is a `build-${provider}-${distro}-${version}` pattern target that will parse out the parts from the target name. Other pattern targets end up calling this target setting the various `ADDITIONAL_OVERRIDES` or `ADDITIONAL_ARGS`. They then provide the following pattern targets:
`${provider}-${distro}-${version}_fips`
`${provider}-${distro}-${version}_offline`
`${provider}-${distro}-${version}_offline-fips`
`${provider}-${distro}-${version}_nvidia`
All the existing targets are now just aliases to the dynamic pattern targets. In the future if we stay consistent with the image name pattern we have for aws/azure/vsphere, we won't have to have any alias patterns and can just setup CI to …
> chore(make): reorg build targets and add Azure

- Dockerfile
- Dockerfile.devkit
- requirements-devkit.txt
- requirements.txt
The devkit is currently failing to build due to conflicting versions of `psutil` being installed vs needed (`alpine` has 5.8 and `azure-cli` requires 5.9).
To remedy this, move the requirements and pining of what we actually care about into `requirements.txt` and `requirements-devkit.txt`. This allows pip to satisfy all the requirements as binary wheels currently, and will allow us to use dependabot in the future to manage bumping the versions. 
```release-note
```
> chore(devkit): fix python packages

- pkg/app/build.go
- pkg/app/config.go
Allows sharing a common base image with the `-nvidia` override.
When building extra images (gpu, fips, etc) the name of the resulting image should include that build extra to prevent conflicts if an account has, for example, RHEL8 and RHEL8 with GPU. Currently both images will attempt to be stored as RHEL8 and only the first will succeed. 
Broke this commit out from #323 as that is blocked on Azure GPU capacity, and its valid for fips images as well.
```release-note
```
> fix(azure): append build name to image sku

- Makefile
Adds a v1 that now get appended during tagged builds which goreleaser runs. The normal builds seem to not use goreleaser so tests should not be affected.
```release-note
```
> fix: adds a v1 to copy path

- images/ova/rhel-79.yaml
- images/ova/rhel-84.yaml
- pkg/packer/manifests/vsphere/packer.json.tmpl
This is one of the first PR to help cleanup vSphere environment and automate it.
- Removes extra release keyword from the name of the template: `konvoy-ova-vsphere-rhel-79-release-release-1.22.8+fips.0-1652280664`
- Removes `ova-vsphere` keyword to allow more room in the VM name. The VM name length is limited. 
We are planning to add KIB version in the name of the release template so that we can automate "lookup" functionality when running e2e tests. This will help make image lookup similar as we do in AWS AMI lookup and avoid creating a PR to change the template name.
- The TC job to create template will add KIB version in the template name. ex. `buildname_extra: release-v1.13.2`
I will file another PR that will cleanup old released template from …
> fix: remove extra "release"  keyword from vsphere template name

- .vscode/settings.json
With this change, vscode-go no longer shows a "duplicate configuration" warning if you happen to use the (up-to-date) `formatting.gofumpt` field in workspace or globally-scoped settings.
```release-note
```
> chore: Update vscode-go settings

- ansible/group_vars/all/defaults.yaml
- ansible/roles/packages/tasks/oracle.yaml
- ansible/roles/packages/tasks/redhat.yaml
- overrides/rhck.yaml
Adds the `oracle_kernel` varaible for ansible. When set to the string `RHCK` it will install the RHCK kernel and set it as the default for the next boot.
* https://jira.d2iq.com/browse/D2IQ-88561
```release-note
```
> feat(oracle): support installing RHCK kernel 

- .github/workflows/release-main.yml
removes invalid working directory param.
this worked with my local tool https://github.com/nektos/act but didn't work with actions where it's not supported according to many people on the actions forums https://github.community/t/unable-to-use-working-directory-with-docker-based-actions/16419/3
```release-note
```
> ci: remove invalid working directory param

- ansible/roles/containerd/tasks/install.yaml
The default `pause` from Containerd was not getting pulled, causing air-gapped tests to fail.
This is because the task to run get the image relies on `containerd` but it was not in the PATH 
See this example where the output is empty https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_E2eCentOS7/3471607?buildTab=log&focusLine=1183&linesState=491
With the fix - https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_E2eCentOS7/3471618?buildTab=log&focusLine=1188&linesState=495
---
Alternatively maybe we should just add the binaries to `/usr/bin` instead of `/usr/local/bin`?
**Does …
> fix: correctly set default pause image

- cmd/konvoy-image/cmd/azure.go
- docs/cli/konvoy-image_build_azure.md
- docs/cli/konvoy-image_generate_azure.md
- pkg/packer/manifests/azure/packer.json.tmpl
Our Azure dev account does not allow creating `Standard_D2ds_v5`. 
* https://jira.d2iq.com/browse/D2IQ-90419
```release-note
```
> fix: use the same instance-type as konvoy

- pkg/packer/manifests/gcp/packer.json.tmpl
Set the `image_family` to something that can be usable in `dkp`.
See companion PR: https://github.com/mesosphere/konvoy2/pull/1411
* https://jira.d2iq.com/browse/D2IQ-90596
```release-note
```
> feat: set a GCP image-family that can be used in dkp

- make/images.mk
We've had a few discussions now with SRE about how we are pushing different artifacts to S3 buckets.
We started by pushing the image and os-packages tars to a staging bucket `konvoy-kubernetes-staging.s3.us-west-2.amazonaws.com` then [a different sync job](https://github.com/mesosphere/docker-repo-sync/blob/d8958f1b25df35ffd863a7f5a4aa20792afe8ef9/sync.sh#L20-L30) is supposed to sync these artifacts to the production `downloads.mesosphere.io` bucket.
There are issues with this approach:
1. The sync job fails pushing the OS packages and image bundles, [see this conversation](https://mesosphere.slack.com/archives/C01MPKVBB5E/p1655830029095139)
2. There is no verification step anyways before the automated sync, so there is little value having it there. …
> ci: use production bucket to download air-gapped artifacts

- .github/workflows/release-main.yml
- .github/workflows/release-tag.yaml
This user should have permissions to run actions. According to the docs the default one will not create an action run https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
```release-note
```
> fix: use other user token that can run actions

- .github/workflows/release-tag.yaml
- .goreleaser.yml
A couple of changes here
1. Just use the tag name -> https://github.community/t/how-to-get-just-the-tag-name/16241/35
2. Have the checksum file include the `v` in the file name
3. Add a `needs` for the notarizing pipeline 
4. uses new checksumfile 
```release-note
```
> fix: various cleanups for release-tag action

- ansible/roles/providers/tasks/qemu.yml
- ansible/roles/providers/tasks/vmware.yml
- ansible/roles/sysprep/tasks/debian.yml
Fixes a couple of minor issues that prevented Ubuntu 20.04 images being built on vSphere:
- Ansible failed when stopping a service that did not exist on a stock install (hv-kvp-daemon)
- /run is mounted with "noexec" by default in Ubuntu which prevented cloud-init scripts from running
No JIRA issue created (I can add one if required)
As discussed in #konvoy channel in D2IQ internal Slack
No, although a new ubuntu image definition could be added to "images/ova" which would make this visible. I have not done so as part of this PR though.
> Ubuntu fixes for vSphere

- cmd/konvoy-image/cmd/artifacts.go
inventory-flag as required is a breaking change. reverts this 
https://github.com/mesosphere/konvoy2/pull/1499
```release-note
```
> fix: remove mark inventory file as required

- .goreleaser.yml
Backports our goreleaser which breaks our signing workflow https://github.com/mesosphere/konvoy-image-builder/runs/7441613471?check_suite_focus=true#step:12:1
```release-note
```
> backport: goreleaser from main to 1.17

- ansible/roles/kubeadm/tasks/main.yaml
- ansible/roles/sysprep/tasks/main.yml
Move disabling swap and firewalld out of sysprep where it only runs for cloud images to a playbook that always runs (including preprovisioned).
Moved it into the `kubeadm` role since these are kubeadm/Kubernetes requirements. 
```release-note
```
> feat: move disabling swap and firewalld to a shared play

- Dockerfile.devkit
- ansible/requirements.txt
- requirements.txt
Bumping Ansible to `4.10.0` which adds support for Rocky Linux https://github.com/ansible/ansible/pull/74530
After Ansible version `v2.10.x` Ansible changed the way the versioning and distribution works, version `v4.x.x` is the first major version that uses ansible-core `v2.11.x`.
```release-note
```
> feat: bump Ansible to 4.10.0

- Makefile
- docs/dev/gcp.md
just some grammar and styles for the gcp dev docs
n/a
solely documentation.
I also changed the file location from
`export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.gcp/credentials.json` to
`export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.gcloud/credentials.json`
Because it's a gcloud cli, and that's what it is in our other docs site. I don't feel strongly about that in particular, but just one for consistency.
solely documentation.
> docs: nits for grammar and style

- ansible/roles/repo/tasks/redhat.yaml
- ansible/roles/sysprep/tasks/redhat.yml
When building centos images on vSphere RHSM is expected. Also unnecessary variables are used. Use ansible internal OS vars instead
```release-note
```
> fix: centos does not need RHSM. Fix ansible conditions

- Dockerfile.devkit
This version comes with https://github.com/mesosphere/mindthegap/pull/185
See https://mesosphere.slack.com/archives/C02GXHVTCPL/p1663163626582799
```release-note
```
> fix: bump mindthegap to preserves image IDs 

- Dockerfile.devkit
- ansible/requirements.txt
- ansible/roles/packages/tasks/debian.yaml
- ansible/roles/providers/tasks/azure-pip.yml
- hack/pip-packages/pip-getter/Dockerfile
- pkg/packer/manifests/aws/packer.json.tmpl
- pkg/packer/manifests/azure/packer.json.tmpl
- pkg/packer/manifests/gcp/packer.json.tmpl
- requirements.txt
- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Fixes various CI flakes.
- fixes intermittent connection failures `Connection to 127.0.0.1 closed` errors
- use repo mirrors to install epel-release rpm instead of using fixed URL to reduce 5XX errors downloading it.
- removes apt `default_release` option when installing kubectl and kubelet packages. after upgrading ansible to 6.3.0, kubectl and kubelet packages were not getting installed with `default_release` for apt set to `kubernetes-xenial`
> fix: upgrade ansible to 6.3.0 and fix CI flakes

- ansible/roles/providers/tasks/vmware.yml
With these three patches (and the ones previously merged) it is now possible to build Ubuntu 20.04 OVAs for vSphere. I have tested these images by building DKP clusters with them, both management and workload and have deployed a full Kommander installation on top.
No JIRA issue for these patches
You may find the following image YAML useful if you want to verify the images yourself:
```yaml
---
download_images: true
build_name: "ubuntu-2004"
packer_builder_type: "vsphere" 
packer:
cluster: ""
datacenter: ""
datastore: ""
folder: ""
insecure_connection: "false"
network: ""
resource_pool: ""
template: "base-ubuntu-2004"
vsphere_guest_os_type: "ubuntu64Guest"
guest_os_type: …
```
> fix: ubuntu  for vsphere 

- ansible/roles/repo/tasks/redhat.yaml
- ansible/roles/sysprep/tasks/redhat.yml
Reported in https://mesosphere.slack.com/archives/C01MPKVBB5E/p1663929389895129
`'Red Hat Enterprise Linux'` was not correct, changing it to `'RedHat'` to match other when conditions for RHEL.
```release-note
```
> fix: incorrect RHEL when condition

- ansible/roles/offline/tasks/upload.yaml
- pkg/app/artifacts.go
gpu won't be defined when we run upload artifacts. we should remove this.
```release-note
```
> fix: upload nvidia runfile for offline preprovisioned 

- ansible/roles/repo/tasks/redhat.yaml
We've seen in internal testing that a machine is already registered. Force register the system. I haven't found anything online that talks about this flag having any negative side-effects.
* https://d2iq.atlassian.net/browse/D2IQ-92155
```release-note
```
> fix: force register RHSM

- ansible/roles/containerd/tasks/suse.yaml
- ansible/roles/packages/tasks/suse.yaml
- ansible/roles/providers/tasks/googlecompute.yml
- ansible/roles/providers/tasks/qemu.yml
- ansible/roles/providers/tasks/vmware.yml
- ansible/roles/sysprep/tasks/suse.yml
- attempt to fix E2E flakes because of following errors. Some `zypper` tasks missing retries. This PR sets same retry and delay for all `zypper` tasks.
```
sles-15-nvidia: TASK [containerd : remove preinstalled containerd] *****************************
sles-15-nvidia: fatal: [default]: FAILED! => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "--disable-repositories", "search", "--type", "package", "--match-exact", "--details", "--installed-only", "containerd"], "msg": "Zypper run command failed with return code 7.", "rc": 7, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<message type=\"error\">System management is locked by the application with pid 4463 (zypper).\nClose this …
```
> fix: add retries when installing SUSE packages 

- ansible/roles/packages/tasks/redhat.yaml
- ansible/roles/sysprep/tasks/redhat.yml
- images/ami/rhel-86.yaml
- images/ova/rhel-86.yaml
- make/ci.mk
- make/images.mk
- builds AMI and OVA for RHEL 8.6 
- fixes to install RHEL 8.6 compatible rpms of NetworkManager, nfs-utils, python3-audit 
* https://d2iq.atlassian.net/browse/D2IQ-92617
```release-note
support for building AMI and OVA for RHEL 8.6
```
> feat: build AMI and OVA for RHEL 8.6 networked, nvidia and airgapped flavors

- make/ci.mk
- make/images.mk
Adds the make targets for rhel86 FIPS.
See https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_BuildAmiRhel86fipsOffline/3656428 and https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_KonvoyImageBuilder_BuildAmiRhel86/3656425 for ✅  runs. 
* https://d2iq.atlassian.net/browse/D2IQ-92617
```release-note
```
> ci: add e2e.build.rhel-8.6-offline-fips target

- overrides/nvidia.yaml
- overrides/offline-nvidia.yaml
- pkg/app/config_test.go
- pkg/app/constants.go
Fixes override files for nvidia by removing unnecessary "nvidia_cuda_version" with a more detailed version of what the driver value should be 
```release-note
```
> fix: nvidia override files with correct information

- ansible/group_vars/all/system.yaml
- overrides/fips.yaml
This is tested in a limit set of OSs, lets not expose it yet to users.
The value is already being set to `false` in https://github.com/mesosphere/konvoy-image-builder/blob/d226e7aeec35229c31f510a9862daecda6595c10/ansible/group_vars/all/system.yaml#L22-L24
```release-note
```
> fix: remove fips.configure from a user facing override

- pkg/packer/manifests/azure/packer.json.tmpl
- pkg/packer/manifests/vsphere/packer.json.tmpl
- adds `kubernetes_version` to vsphere `manifest.json` 
- adds `compute_gallery_image_id` for azure `manifest.json`
- remove unused custom output fields from vsphere manifest.json
* https://d2iq.atlassian.net/browse/D2IQ-93782
> fix: add image_name and kubernetes_version to all infrastructure's outtput manifest.yaml

- make/ci.mk
- make/images.mk
This allows for the makefile targets to build rhel 8.6 offline gpu and also fixes building for rhel.
* https://jira.d2iq.com/browse/D2IQ-92651
```release-note
```
> build: enable Nvidia offline for rhel 8.6

- ansible/roles/fips/tasks/main.yaml
This is need because the `fips.enabled` in `override/fips.yaml` key overrides the whole fips map, removing `fips.configure`
```release-note
```
> fix: fips.configure default value

- ansible/molecule/default/molecule.yml
- ansible/molecule/default/tests/test_default.py
- ansible/roles/providers/tasks/misc.yml
- ansible/roles/repo/defaults/main.yaml
- feature flags for ubuntu 20.04 not set due to regex and version missmatch. 
- on centos 7.9 no featureflags set due to cloud-init sending version string on stderr 
- supersceedes #548 
* https://jira.d2iq.com/browse/D2IQ-93868
```release-note
fix: cloud-init feature flags where not set on ubuntu 20.04 leading to images not being usable by CAPI
```
> fix: set feature flag for cloud-init to ignore errors

- ansible/molecule/default/molecule.yml
- ansible/molecule/default/tests/test_default.py
- ansible/roles/providers/tasks/misc.yml
- ansible/roles/repo/defaults/main.yaml
- feature flags for ubuntu 20.04 not set due to regex and version missmatch. 
- on centos 7.9 no featureflags set due to cloud-init sending version string on stderr 
- supersceedes #548 
* https://jira.d2iq.com/browse/D2IQ-93868
this is a cherry-picked backport of #550 
```release-note
fix: cloud-init feature flags where not set on ubuntu 20.04 leading to images not being usable by CAPI
```
>   fix: set feature flag for cloud-init to ignore errors

- images/ami/rhel-82.yaml
- pkg/packer/manifests/aws/packer.json.tmpl
- pkg/packer/manifests/azure/packer.json.tmpl
- pkg/packer/manifests/gcp/packer.json.tmpl
- pkg/packer/manifests/vsphere/packer.json.tmpl
This PR supports packer provisioning with STIG requirements by using the `remote_folder` parameter in packer to override the default `/tmp` directory.
* https://jira.d2iq.com/browse/D2IQ-93657/
- @supershal and I tested using a custom `source_ami` image in `rhel-82.yaml` where we remounted the `/tmp` directory with the `noexec` flag to match STIG requirements. We also commented out `ami_filter_name` and `ami_filter_owners`.
> fix: Can not specify custom Packer directory 

- .goreleaser.yml
- Dockerfile
- Dockerfile.devkit
- Makefile
- README.md
- cmd/konvoy-image-wrapper/cmd/wrapper.go
- cmd/konvoy-image-wrapper/cmd/wrapper_test.go
- cmd/konvoy-image-wrapper/main.go
- cmd/konvoy-image/cmd/gcp.go
- make/ci.mk
- make/images.mk
- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
- Use konvoy image wrapper binary as default for all CI build targets (TC configuration does not needs to be changed)
- This will make the CI runs same as how production users would use KIB
- Remove using `konvoy-image` binary for running image build targets
- Replace direct use of `devkit` container to run `konvoy-image` binary. 
- Refactor `wrapper.go` (first pass) to better organize code
- start using `make build-wrapper` instead of `make build` for development. All dependency required for building wrapper will be handled by Makefile targets automatically. 
- **Enable running konvoy-image command on Mac without Sudo access, hacking Makefile, changing file permissions,  propagating env variables to sudo etc**
* …
> chore: use konvoy image wrapper for  build targets 

- .github/workflows/release-tag.yaml
GoReleaser runs in a container and then more steps from goreleaser also run in containers. This simplifies the workflow and should reduce build time as well
```release-note
```
> ci: run goreleaser not in a container 

- ansible/roles/packages/tasks/install-redhat.yaml
Backport https://github.com/mesosphere/konvoy-image-builder/pull/205
* https://d2iq.atlassian.net/browse/D2IQ-93793
```release-note
```
> [release-1.5][BACKPORT] fix:skip adding GPG key when offline mode is enabled

- ansible/roles/config/templates/config.toml.tmpl
- ansible/roles/containerd/tasks/install-flatcar.yaml
> fix: Configure containerd runc plugin options with systemd cgroup driver

- ansible/roles/config/templates/config.toml.tmpl
- ansible/roles/containerd/tasks/install-flatcar.yaml
backports #493 
```release-note
```
> fix: Configure containerd runc plugin options with systemd cgroup drivers 

- Makefile
Enable debugging for goreleaser, should make debugging release failures easier.
```release-note
```
> ci: enable debug for goreleaser release

- ansible/roles/containerd/tasks/install.yaml
Workaround for issue that affects the kernel used by RHEL 7.9, CentOS 7.9, and Oracle Linux 7.9. For issue, see https://bugzilla.redhat.com/show_bug.cgi?id=1441737.
* https://d2iq.atlassian.net/browse/D2IQ-94574
```release-note
```
> fix: Enable fs.may_detach_mounts kernel parameter on RHEL 7.9, and variants

- ansible/roles/setup_versionlock/tasks/suse.yaml
Sometimes, another instance of zypper is running when KIB calls zypper to install packages. 
```console
sles-15: TASK [setup_versionlock : check if versionlock exists] *************************
sles-15: fatal: [default]: FAILED! => {"changed": false, "cmd": ["zypper", "locks", "-s"], "delta": "0:00:00.040021", "end": "2022-12-01 21:00:39.553172
", "msg": "non-zero return code", "rc": 7, "start": "2022-12-01 21:00:39.513151", "stderr": "System management is locked by the application with pid 4219 (z
ypper).\nClose this application before trying again.", "stderr_lines": ["System management is locked by the application with pid 4219 (zypper).", "Close thi
s application before trying again."], "stdout": "", "stdout_lines": []}
```
~This may be due to the …
> fix: allow existing zypper process to finish and release lock

- ansible/roles/networking/tasks/main.yaml
checks before enabling ipv6 forwarding if ipv6 is present
* https://d2iq.atlassian.net/browse/D2IQ-94653
```release-note
checks if ipv6 is enabled to set forwarding
```
> fix: dont ipv6 forward if you dont have ipv6 forwarding file 

- Makefile
On Mac, there was an extra trailing slash on the `REPO_ROOT_DIR` variable. This checks for and removes it
Needs to be checked on Linux. When running `make docker-build-amd64`,
In the Dockerfile path outputted here:
```
docker buildx build \
-t docker.io/mesosphere/konvoy-image-builder:v1.25.2-25-g6d41e49e620f-devkit-arm64 \
--build-arg USER_ID=502 --build-arg GROUP_ID=20 --build-arg USER_NAME=marykarroqe --build-arg GROUP_NAME=staff --build-arg DOCKER_GID=1 --build-arg BUILDARCH=arm64 --platform linux/arm64 --file /Users/marykarroqe/go/src/github.com/mesosphere/konvoy-image-builder/Dockerfile.devkit  \
```
`--file …
> ci: added --no-cache and fixed trailing slash path issue

- ansible/roles/images/tasks/check-or-pull-images.yaml
Otherwise this play is not idempotent and would fail with: "ctr: image "k8s.gcr.io/coredns:v1.9.3": already exists"
```release-note
```
> fix: use --force when retagging CoreDNS image

- ansible/group_vars/all/defaults.yaml
- ansible/roles/kubeadm/tasks/debian.yaml
The cri-tools package is a dependency of kubeadm. However, kubeadm installs the latest cri-tools version. And while the kubeadm is compatible with the container runtime, the latest cri-tools version may not be.
For example, on January 20, 2023, kubeadm v1.25.x installs cri-tools v1.26.0. The former is compatible with containerd v1.5.x, but the latter is not.
Please see https://github.com/kubernetes/release/issues/2866 for more details.
* https://d2iq.atlassian.net/browse/D2IQ-95429
```release-note
On Debian-based Linux distributions, install a version of the cri-tools package known to be compatible with both the Kubernetes and …
```
> feat: Install specific cri-tools package on debian derivatives

- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
- vsphere datastore `ovh-nfs` is deprecated. moving the template creation to `ovh-netapp-users`
> ci: change vsphere e2e test's datastore to ovh-netapp-users

- images/ami/centos-7.yaml
* fix: use new centos 7.9 base AMI
We need this to be able to run CentOS 7.9 tests for this and any new PRs for release-1.5 
* https://d2iq.atlassian.net/browse/D2IQ-94286
```release-note
```
> fix: use new centos 7.9 base AMI (#573)

- ansible/group_vars/all/defaults.yaml
- ansible/roles/kubeadm/tasks/debian.yaml
- ansible/roles/packages/tasks/flatcar.yaml
Upstream kubeadm packages will pull in the latest cri-tools, which may be incompatible with the installed container runtime. For KIB v1.17.x, kubeadm v1.24.6 pulls in cri-tools v1.26.0, which is incompatible with containerd v1.4.13.
The kubeadm v1.24.6 package was released after https://github.com/kubernetes/release/commit/5e6ea972a71975172f1bb91cdec40bd48b2801dc merged, so the package requires cri-tools v1.25.0 or higher. Since v1.26.0 is incompatible with containerd v1.4.13, we will use v1.25.0.
On flatcar Linux, KIB will continue to install cri-tools v1.22.0.
* https://d2iq.atlassian.net/browse/D2IQ-95429
v1.22.0 is not among the …
> [release-1.24] feat: Use cri-tools v1.25.0 for Debian derivatives

- ansible/group_vars/all/defaults.yaml
- ansible/roles/kubeadm/tasks/debian.yaml
- ansible/roles/packages/tasks/flatcar.yaml
Upstream kubeadm packages will pull in the latest cri-tools, which may be incompatible with the installed container runtime. For KIB v1.17.x, kubeadm v1.23.12 pulls in cri-tools v1.26.0, which is incompatible with containerd v1.4.13.
The kubeadm v1.23.12 package was released after https://github.com/kubernetes/release/commit/5e6ea972a71975172f1bb91cdec40bd48b2801dc merged, so the package requires  cri-tools v1.25.0 or higher. Since v1.26.0 is incompatible with containerd v1.4.13, we will use v1.25.0.
On flatcar Linux, KIB will continue to install cri-tools v1.22.0.
* https://d2iq.atlassian.net/browse/D2IQ-95429
```release-note …
```
> [release-1.19] feat: Use cri-tools v1.25.0 for Debian derivatives

- ansible/group_vars/all/defaults.yaml
- ansible/roles/kubeadm/tasks/debian.yaml
- ansible/roles/packages/tasks/flatcar.yaml
Upstream kubeadm packages will pull in the latest cri-tools, which may be incompatible with the installed container runtime. For KIB v1.17.x, kubeadm v1.22.8 pulls in cri-tools v1.26.0, which is incompatible with containerd v1.4.13.
cri-tools v1.22.0 is not among the [deb](https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages) or [rpm](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) packages published by kubernetes. Because the kubeadm package has already been installing the latest available cri-tools package, we use v1.23.0, the oldest available and compatible version.
On flatcar Linux, KIB will continue to install cri-tools v1.22.0.
* …
> [release-1.17] feat: Use cri-tools v1.23.0 on debian derivatives

- ansible/group_vars/all/defaults.yaml
- ansible/roles/packages/tasks/install-debian.yaml
- ansible/roles/packages/tasks/install-flatcar.yaml
Upstream kubeadm packages will pull in the latest cri-tools, which may be incompatible with the installed container runtime. For KIB v1.5.x, kubeadm v1.21.6 pulls in cri-tools v1.26.0, which is incompatible with containerd v1.4.11.
cri-tools v1.21.0 is not among the [deb](https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages) or [rpm](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) packages published by kubernetes. Because the kubeadm package has already been installing the latest available cri-tools package, we use v1.23.0, the oldest available and compatible version.
On flatcar Linux, KIB will continue to install cri-tools v1.22.0.
* …
> [release-1.5] feat: Use cri-tools v1.23.0 for Debian derivatives

- ansible/roles/config/templates/config.toml.tmpl
- revert nvidia configuration changes made by https://github.com/mesosphere/konvoy-image-builder/pull/585
The changes in https://github.com/mesosphere/konvoy-image-builder/pull/585 was made to support GPU using nvidia operator.  This feature is not available in `release-1.19.x` so reverting it back to the original configuration.
> fix: configure containerd runc plugin for nvidia

- Makefile
Removed docker-driver buildx instance for faster builds 
```release-note
```
> ci: don't use docker-container driver

- .github/workflows/release-kib.yaml
Prevents CAPPP bump in case of KIB release failure
> ci: bump CAPPP on successful release jobs

- .github/workflows/azure-e2e.yaml
- images/azure/rocky-90.yaml
- magefile.go
- We support only Rocky 9.0 for azure. This PR fixes incorrect references used for rocky linux 9.0 azure builds.
> fix: build rocky linux 9.0 azure image

- .github/workflows/release-gcp-template.yaml
- .github/workflows/release-vsphere-template.yaml
Creates vSphere templates and GCP images and persists them in respective cloud service. 
These images are later used in the konvoy e2e tests.
> ci: create vSphere template and GCP image on release tag

- .github/workflows/release-kib.yaml
Checkout CAPPP repo before running Action to install GO.
Determine go version based on CAPPP's go.mod file.
> ci: fix KIB to CAPPP bump job

- .github/workflows/aws-e2e.yaml
- .github/workflows/azure-e2e.yaml
- .github/workflows/gcp-e2e.yaml
- .github/workflows/release-ami.yaml
- .github/workflows/release-azure.yaml
- .github/workflows/release-gcp-template.yaml
- .github/workflows/release-kib.yaml
- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
- allow user to trigger GHA build manually.
> ci: enable manual trigger for GHA build and e2e jobs

- .gitignore
- magefile.go
- adds `-release`, `-fips-release`, `-nvidia-release` as build name extra to release names.
- This will enable konvoy e2e tests to find released AMIs directly.
Tested by creating release AMI locally: `"konvoy-ami-rocky-9.1-release-1.25.4-20230210213910"`
> ci: add build metadata to the released image name

- ansible/roles/repo/tasks/redhat.yaml
Seen in Azure where `$releasever` is not being correctly replaced, but can happen in other images
I was able to repro this issue in Azure and test this fix, see:
```
TASK [repo : add alma linux extra repository] **********************************
changed: [20.228.111.34]
TASK [repo : install epel-release for RHEL 8.x] ********************************
changed: [20.228.111.34]
TASK [repo : find epel-release repo files] *************************************
ok: [20.228.111.34]
TASK [repo : set $releasever variables in epel-release repo files] *************
changed: [20.228.111.34] => (item={'path': '/etc/yum.repos.d/epel-modular.repo', 'mode': '0644', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, …
```
> fix: epel repos not working with some RHEL images

- .github/workflows/aws-e2e.yaml
- ansible/group_vars/all/system.yaml
- ansible/provision.yaml
- ansible/roles/gpu/tasks/nvidia-gpu-RHEL.yaml
- ansible/roles/repo/tasks/redhat.yaml
- ansible/roles/sysprep/tasks/redhat.yml
Subscribe to the appropriate repos from redhat to fetch kernel headers.
Fall back to environment variables if rhsm_user and rhsm_password are not present 
Allows user to use activation key to subscribe to redhat subscription manager 
*https://d2iq.atlassian.net/browse/D2IQ-95717
```release-note
Subscribe to the appropriate repos from redhat to fetch kernel headers.
Fall back to environment variables if rhsm_user and rhsm_password are not present 
Allows user to use activation key to subscribe to redhat subscription manager 
```
> fix: use subscription manager to get kernel headers

- ansible/roles/sysprep/tasks/redhat.yml
Fixes an issue where the Oracle AMI would not start.
The base Oracle7 image has `IPADDR` `GATEWAY` and `DNS1` set that prevented the instance from starting, this change will clear those values.
* https://d2iq.atlassian.net/browse/D2IQ-95718
```release-note
```
> fix: netwmanager config for OracleLinux 7

- ansible/provision.yaml
Using a `rescue` section hides errors in the failed task. From docs:
> If an error occurs in the block and the rescue task succeeds, Ansible
> reverts the failed status of the original task for the run and continues
> to run the play as if the oriinal task had succeeded. The rescued task
> is considered successful
In this case we want the error to be propagated, and should use an
`always` section to ensure the machine is unregistered from RHSM.
Tested locally and it works for me if there is a failure in any task then the always section runs and exits correctly:
```
amazon-ebs.kib_image:
amazon-ebs.kib_image: TASK [Remove subscriptions] ****************************************************
amazon-ebs.kib_image: skipping: [default]
amazon-ebs.kib_image:
amazon-ebs.kib_image: TASK [Unregister …
```
> fix: Use always section instead of rescue to remove RHEL subscription

- .github/workflows/aws-e2e.yaml
- .github/workflows/azure-e2e.yaml
- .github/workflows/gcp-e2e.yaml
- .github/workflows/release-ami.yaml
- .github/workflows/release-azure.yaml
- .github/workflows/release-gcp-template.yaml
- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
We want:
1. Run all jobs in parallel (`strategy.max-parallel: N`)
2. Let all jobs complete (`strategy.fail-fast: false`)
3. Fail the run if any job fails (do not use `continue-on-error` in any job)
We already have (1) and (2). With this commit, we get (3). Previously, the run would pass, even if some job failed.
```release-note
```
> ci: Fail workflow run if any job fails

- Dockerfile
- Dockerfile.devkit
- ansible/requirements.txt
- ansible/roles/offline/tasks/upload.yaml
- docs/dev/ansible-modules.md
- requirements.txt
The single largest component (approximately 42%, 331MB out of 791MB) in the KIB image is the ansible collections install.
```
/ # du -hmd4 | sort -nr | head -n20
791	.
729	./usr
434	./usr/lib
427	./usr/lib/python3.9
384	/usr/lib/python3.9/site-packages/
331	/usr/lib/python3.9/site-packages/ansible_collections
```
I believe we only need to use two collections (`community.general` and `ansible.posix`), which need  about 20MB:
```
/usr/lib/python3.9/site-packages/ansible_collections # du -hmd2 | egrep "posix|general"
19	./community/general
1	./ansible/posix
```
```release-note
```
> feat: Install only required ansible collections 

- ansible/roles/sysprep/tasks/main.yml
Fix from https://github.com/kubernetes-sigs/image-builder/pull/739/files#diff-2f3020c3867a75d1e2395d10238225e0fa343e8097cb434f647817e446354a88R149
Looks like when using `root` as the SSH user, `ansible_env.SUDO_USER` is not set.
Fallback to using `ansible_user_id` which will in this case already equal the ssh user.
```release-note
```
> fix: fallback to ansible_user_id when using root user

- .github/workflows/aws-e2e.yaml
- .github/workflows/release-ami.yaml
I noticed the Rocky FIPS offline tests were failing. I was going to try and fix it, but actaully Rocky FIPS is not supported.
Removing the e2e and release GHA configs.
* https://d2iq.atlassian.net/browse/D2IQ-96173
```release-note
```
> ci: remove Rocky 9.1 FIPS builds

- .github/workflows/release-kib.yaml
- `make update-kib` in https://github.com/mesosphere/konvoy-image-builder/blob/main/.github/workflows/release-kib.yaml#L69 does not require go to be installed. This PR removes setting up go environment when bumping the kib version in CAPPP
> ci: stop setting go env for bump-kib in CAPPP github job

- .github/workflows/build.yml
- .github/workflows/unit-test.yml
- Dockerfile.devkit
- Makefile
saves us 8 minutes from running a devkit build for our unit tests, it just needs go. also we dont use the codecov report so get rid of that as well
```release-note
```
> ci: remove devkit from unit tests 

- .github/workflows/vsphere-e2e.yaml
- ansible/roles/containerd/tasks/main.yaml
- ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/max-files.conf
- ansible/roles/repo/tasks/redhat.yaml
- cmd/konvoy-image-wrapper/cmd/wrapper.go
- pkg/packer/manifests/vsphere/packer.pkr.hcl
https://d2iq.atlassian.net/browse/D2IQ-96107
This change in contained seems to cause problems for workloads that use disk https://github.com/containerd/containerd/pull/4475
```release-note
```
> fix: set limitnofile

- pkg/packer/manifests/azure/packer.pkr.hcl
The `compute_gallery_image_id` in the manifest contains an extra `}` what makes CAPZ to fail to find this image.
This commit removes the extra wrong character.
https://jira.d2iq.com/browse/D2IQ-DIDNCREATEONE
```release-note
fixes the azure `compute_gallery_image_id` on the `manifest.json` file
```
> fix: set correct compute_gallery_image_id

- .github/workflows/release-kib.yaml
- .goreleaser.yml
- Makefile
- hack/release.sh
Its very difficult to spot failures in goreleaser build hooks. Even in debug mode goreleaser swallows stdout/stderr of the scripts running in the pre build hooks. This resulted in very time consuming mechanism to figure out actual issue with goreleaser.
Latest go releaser has this fixed with `output:true` https://goreleaser.com/customization/builds/#build-hooks
This PR upgrades go releaser and sets output:true setting.
```release-note
```
> ci: print output of the goreleaser build hook 

- cmd/konvoy-image-wrapper/cmd/wrapper.go
This commit removes the instruction to copy the stdin in the docker wrapper and set tty to true is some cases. We don't need that since we don't expect KIB to read from stdin.
* https://jira.d2iq.com/browse/D2IQ-NOTCREATED
```release-note
```
> feat: do not copy stdin and set tty to false 

- ansible/roles/containerd/tasks/redhat.yaml
We found that some network failures lasted longer than 9s.
* https://d2iq.atlassian.net/browse/D2IQ-93681
I think exponential backoff would have been nice to use, but Ansible does not support it, despite a misleading example in the documentation https://github.com/ansible/ansible/issues/75794.
```release-note
```
> fix: Retry containerd yum/rpm tasks up to 30s

- hack/vsphere/main.tf
- images/ova/rhel-79.yaml
- images/ova/rhel-84.yaml
- images/ova/rhel-86.yaml
* ci: update vsphere bastion base template defaults
* fix: change location of base template
* fix: use OS qualification templates for KIB e2e tests
* fix: ubuntu template
---------
```release-note
```
> [backport 1.24] ci: update vsphere base template defaults

- ansible/roles/containerd/tasks/redhat.yaml
We found that some network failures lasted longer than 9s.
* https://d2iq.atlassian.net/browse/D2IQ-93681
```release-note
```
> [backport release-1.24] fix: Retry containerd yum/rpm tasks up to 30s 

- Dockerfile
- Dockerfile.devkit
Installing ansible collection is the most time consuming step when building KIB container image. Caching it in devkit container should save around `1m30s` when building the image.
Tested locally.
```bash
❯ docker run --entrypoint '/bin/sh' -it --rm mesosphere/konvoy-image-builder:v2.2.1-15-ge02168df3248-amd64
~ # ls
ansible  images   packer
~ # ls /usr/share/ansible/collections/ansible_collections/
ansible                       ansible.posix-1.5.1.info      community
ansible.netcommon-5.0.0.info  ansible.utils-2.9.0.info      community.general-6.4.0.info
~ # ansible-galaxy collection list
Collection        Version
----------------- …
```
> build: cache ansible collections in devkit image

- Dockerfile
- Dockerfile.devkit
The latest ansible plugin `community.general` `6.5.0` breaks existing behavior of the `redhat_subscription` module. Issue: https://github.com/ansible-collections/community.general/issues/6258
As a result kib jobs fails when running RHEL builds in non-airgapped mode.
As a workaround, this PR pins ansible plugin versions.
> fix: pin ansible collection versions

- .github/workflows/aws-e2e.yaml
- .github/workflows/azure-e2e.yaml
- .github/workflows/build-devkit-image.yaml
- .github/workflows/gcp-e2e.yaml
- .github/workflows/run-all-e2e-tests.yaml
- .github/workflows/vsphere-e2e.yaml
- Dockerfile.devkit
- Makefile
- README.md
- Simplifies conditions to execute e2e jobs
- One job to control execution of all the e2e tests on a PR label
- Ensure devkit image is available on dockerhub before running tests
- Make it easy to navigate all e2e tests for current PR in one place in GHA UI
```release-note
```
> ci: execute all e2e tests on PR label with one GHA workflow

- ansible/roles/repo/defaults/main.yaml
- ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
- ansible/roles/repo/tasks/redhat.yaml
- images/common.yaml
This PR is stacked on https://github.com/mesosphere/konvoy-image-builder/pull/781
Installs epel release for RHEL/Centos 7.9 using static repo files
> fix: install epel repo in RHEL 7 using static repo file

- cmd/konvoy-image-wrapper/cmd/wrapper.go
set SSH_PRIVATE_KEY_FILE env variable for docker  wrapper
* https://d2iq.atlassian.net/browse/D2IQ-93836
Tested the fix manually. The CI jobs uses SSH agent to add private key to the GHA runner's ssh agent.
> fix: set SSH_PRIVATE_KEY_FILE env variable for docker  wrapper

- .goreleaser.yml
The packer directory removed in recent refactoring. But I didnt realized to remove it from `.goreleaser.yaml` file. 
This was caught when creating release. https://github.com/mesosphere/konvoy-image-builder/actions/runs/4863493893/jobs/8671278222#step:8:3080
> fix: remove packer directory from goreleaser configuration

- Dockerfile.devkit
backport mindthegap bump to release-2.2
* https://d2iq.atlassian.net/browse/D2IQ-96732
> fix: backport mindthegap bump to release-2.2

- .github/workflows/aws-e2e.yaml
- .github/workflows/azure-e2e.yaml
- .github/workflows/build-devkit-image.yaml
- .github/workflows/build.yml
- .github/workflows/conventional-label.yaml
- .github/workflows/gcp-e2e.yaml
- .github/workflows/lint.yml
- .github/workflows/next-release-version.yml
- .github/workflows/release-ami.yaml
- .github/workflows/release-azure.yaml
- .github/workflows/release-gcp-template.yaml
- .github/workflows/release-kib.yaml
- .github/workflows/release-vsphere-template.yaml
- .github/workflows/scorecards.yml
- .github/workflows/sync-cli-docs.yaml
- .github/workflows/unit-test.yml
- .github/workflows/vsphere-e2e.yaml
There were some workflows that still had the wrong labelled runners or were using githubs runners, we need to change them to org-wire-runners so we have a more coherent understanding of our infrastructure. This pr will be used to understand which workflows require which size or if they need kind cluster. Please check the the runners in the change made and use [this](https://github.com/mesosphere/github-action-runners-deployment#how-to-add-an-org-wide-runner-to-your-repos-workflow) as a criteria. Once the sizes have been confirmed the pr we can merge.
Which issue(s) does this PR fix?:
https://jira.d2iq.com/browse/D2IQ-97191
```release-note
```
> ci: changed runner labels 

- images/ami/flatcar.yaml
In DKP 2.5 DKP switched to supporting the Flatcar LTS version, switching the TF lookup vars to find the [latest LTS version](https://d2iq.slack.com/archives/C04DTKTM6N6/p1686065076613979?thread_ts=1686056418.770459&cid=C04DTKTM6N6).
Removed `source_ami` as `ami_filter_name` takes precedence. 
* https://d2iq.atlassian.net/browse/D2IQ-97410
```release-note
```
> ci: use Flatcar LTS version in e2e tests

- .golangci.yml
New version of golangci-lint pulled in a new version of depguard that changed the API, see https://github.com/golangci/golangci-lint/issues/3877
```release-note
```
> ci: use new depguard config

- .gitignore
- Makefile
- ansible/group_vars/all/defaults.yaml
- ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/containerd.service
- ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/docker.service
- ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/docker.socket
- ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/prepare-docker.service
- ansible/roles/containerd/tasks/install-flatcar.yaml
Flatcar 3033.3.x LTS ships with docker version [20.10.12](https://docs.docker.com/engine/release-notes/20.10/#201012) which is shipped with 1.5.x of containerd that is [incomaptible with k8s 1.26](https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/#cri-v1alpha2-removed).
In order to workaround above, this change adds support to upgrade the docker version in flatcar lts 3033.3.x to [20.10.15](https://docs.docker.com/engine/release-notes/20.10/#201015) - which is three patch versions ahead compared to upstream - and thus ensures that 1.6.x of containerd is available for kubelet to start successfully. 
References:
- https://www.flatcar.org/docs/latest/container-runtimes/use-a-custom-docker-or-containerd-version/
- …
> fix: upgrade docker in flatcar 3033.3.x LTS for k8s 1.26 support

- ansible/roles/repo/tasks/redhat-offline.yaml
This an issue thats wasn't caught in KIB tests because there are no upgrade tests here (as there shouldn't be).
This did not fail in Konvoy's e2e air-gapped preprovisioned upgrad tests [because the package there was rebuilt more recently](https://teamcity.mesosphere.io/buildConfiguration/MesosphereOnly_ClosedSource_DkpReleases_OsPackagesBundles_CentOS7nonFips?branch=v1.26.3&buildTypeTab=overview&mode=builds), but the [FIPS packages were not](https://teamcity.mesosphere.io/buildConfiguration/MesosphereOnly_ClosedSource_DkpReleases_OsPackagesBundles_CentOS7fips?branch=v1.26.3&mode=builds).
I'm going to add a Konvoy FIPS preprovisioned upgrade test that would have caught this kind of issue in future. I ran the test with a customer KIB image built with …
> fix: force update the offline repo metadata cache

- Dockerfile
- Dockerfile.devkit
- pkg/packer/manifests/aws/packer.pkr.hcl
- pkg/packer/manifests/azure/packer.pkr.hcl
- pkg/packer/manifests/gcp/packer.pkr.hcl
- pkg/packer/manifests/vsphere/packer.pkr.hcl
- Forked https://github.com/YaleUniversity/packer-provisioner-goss to https://github.com/supershal/packer-plugin-goss to make it compatible with conventions dictated by latest packer plugin architecture.
- Using the forked packer plugin to simplify goss installation. This will help migrate KIB to new architecture.
> chore: simplify installation of Goss plugin for packer

- .github/workflows/confluence-docs.yaml
Adds a Github workflow to trigger Confluence version updates whenever there is a new release.
See https://github.com/mesosphere/dkp-infra-tools/pull/178 for test run
* https://jira.d2iq.com/browse/D2IQ-91592
Depends on https://github.com/mesosphere/dkp-infra-tools/pull/178
```release-note
```
> chore: Trigger version updates in Confluence

- .github/composite/vcd-e2e/action.yaml
- .github/workflows/release-vcd-template.yaml
- .github/workflows/release-vsphere-template.yaml
- .gitignore
- test/infra/Makefile
- test/infra/aws/export.sh
- test/infra/vcd/bastion.tf
- test/infra/vcd/upload-template.sh
- test/infra/vcd/variables.tf
- test/infra/vsphere/export.sh
- Script to create a temporary VM in production vCenter environment, download given template and upload it to VCD organization
- Cleanup Makefile that creates and destroys bastion VMs for easier local testing
* https://d2iq.atlassian.net/browse/D2IQ-97576
Test CI job: https://github.com/mesosphere/konvoy-image-builder/actions/runs/5522031816
This PR will allow to invoke this flow manually from GHA UI.
I will file separate PR to kick off this flow when vSphere template is released by the release job.
> ci: upload KIB release template to cloud director organization 

- .gitignore
adding `vsphere-bastion.pub` to `.gitignore` to fix https://github.com/mesosphere/konvoy-image-builder/actions/runs/5904447936/job/16016530437#step:8:4425
> Please check in your pipeline what can be changing the following files:
> ?? vsphere-bastion.pub
```release-note
```
> [release-2.2] chore: update gitignore for vsphere-bastion.pub

- .gitignore
Release builds are failing because it detects new file `vsphere-bastion.pub` in root directory.
https://github.com/mesosphere/konvoy-image-builder/actions/runs/6005402723/job/16288896553#step:8:18
This PR will ignore it so that release can go through.
We should re-tag v2.6.0 after this is merged in.
> chore: git ignore  vsphere-bastion.pub

- ansible/roles/packages/tasks/flatcar.yaml
A pre-provisioned machine never gets restarted after running KIB, so this systemd unit never gets started.
Saw that `kube-controller-manager` in Konvoy e2e test was failing to start because `/user/libexec/kubernetes` was still read only.
Tested locally and with this change the pre-provisioned cluster came up.
* https://d2iq.atlassian.net/browse/D2IQ-98654
```release-note
```
> fix: start usr-libexec.mount to also support pre-provisioned

- ansible/roles/packages/tasks/url.yaml
Force redownload the Kubelet and kubectl binaries for Flatcar.
Without this fix, upgraded Nodes ended up not actually upgrading the Kubelet version.
* https://d2iq.atlassian.net/browse/D2IQ-98984
```release-note
```
> fix: force redownload of Kubelet and kubectl binaries for Flatcar

- ansible/roles/containerd/tasks/install-flatcar.yaml
Don't revert Docker and Containerd systemd unit files when running KIB for a second time after downloading a new version of Docker.
Tested manually by running a pre-provisioned Kubernetes cluster upgrade with a dev image.
* https://d2iq.atlassian.net/browse/D2IQ-98979
```release-note
```
> fix: don't override Docker systemd unit file for Flatcar

- ansible/roles/containerd/tasks/install-flatcar.yaml
Don't revert Docker and Containerd systemd unit files when running KIB for a second time after downloading a new version of Docker.
Tested manually by running a pre-provisioned Kubernetes cluster upgrade with a dev image.
* https://d2iq.atlassian.net/browse/D2IQ-98979
```release-note
```
> [release-2.5] fix: don't override Docker systemd unit file for Flatcar

- ansible/roles/packages/tasks/url.yaml
Force redownload the Kubelet and kubectl binaries for Flatcar.
Without this fix, upgraded Nodes ended up not actually upgrading the Kubelet version.
* https://d2iq.atlassian.net/browse/D2IQ-98984
```release-note
```
> [release-2.5] fix: force redownload of Kubelet and kubectl binaries for Flatcar

- ansible/roles/packages/tasks/url.yaml
Force redownload the Kubelet and kubectl binaries for Flatcar.
Without this fix, upgraded Nodes ended up not actually upgrading the Kubelet version.
* https://d2iq.atlassian.net/browse/D2IQ-98984
```release-note
```
> [release-2.2] fix: force redownload of Kubelet and kubectl binaries for Flatcar

- ansible/roles/packages/tasks/url.yaml
Force redownload the Kubelet and kubectl binaries for Flatcar.
Without this fix, upgraded Nodes ended up not actually upgrading the Kubelet version.
* https://d2iq.atlassian.net/browse/D2IQ-98984
```release-note
```
> [release-1.24] fix: force redownload of Kubelet and kubectl binaries for Flatcar

- .github/workflows/aws-e2e.yaml
- ansible/group_vars/all/defaults.yaml
- ansible/roles/version/templates/kubeadm-conf.yaml.tmpl
- images/common.yaml
- test/infra/vsphere/variables.tf
K8s upgrade
* https://d2iq.atlassian.net/browse/D2IQ-97979
According to https://github.com/kubernetes/kubernetes/blob/v1.27.5/cluster/gce/gci/configure.sh#L35, K8s 1.27.5 is still using crictl 1.26.0, so no need to upgrade.
```release-note
```
> feat: Upgrade Kubernetes version to 1.27.5

- .github/workflows/vsphere-e2e.yaml
- Dockerfile
- Dockerfile.devkit
- cmd/konvoy-image-wrapper/cmd/wrapper.go
- images/ova/rhel-79.yaml
- images/ova/rhel-84.yaml
- images/ova/rhel-86.yaml
- images/ova/rocky-91.yaml
- images/ova/ubuntu-2004.yaml
- pkg/packer/manifests/vsphere/packer.pkr.hcl
- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
- test/infra/vsphere/variables.tf
Bumps alpine to 3.15.6, the oldest possible version with zlib CVE patch: https://gitlab.alpinelinux.org/alpine/aports/-/commit/41216b729e439cc0ba91320e82962b51f163591e
* https://jira.d2iq.com/browse/D2IQ-99081
```release-note
```
> fix: bump alpine from 3.15.4 to 3.15.6

- ansible/roles/config/templates/kubelet-drop-in.conf
https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/#removal-of-container-runtime-command-line-argument removes deprecated command line argument. entirely unclear why some tests are passing. I found this error on an azure machine
```
Sep 12 00:39:45 faiq-test15-control-plane-gsphw kubelet[2392]: E0912 00:39:45.346378    2392 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --container-runtime"
```
```release-note
```
> fix: remove deprecated cmdline argument

- Dockerfile
Bumps alpine to 3.15.6, the oldest possible version with zlib CVE patch: https://gitlab.alpinelinux.org/alpine/aports/-/commit/41216b729e439cc0ba91320e82962b51f163591e
```release-note
```
> fix: bump alpine from 3.15.4 to 3.15.6 to patch zlib CVE

- ansible/roles/packages/tasks/debian.yaml
The latest cloud-init version `23.3.1-0ubuntu1~20.04.1` is unable to run `boothook` https://cloudinit.readthedocs.io/en/latest/explanation/format.html#cloud-boothook provided by CAPA, https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/0bf78b04b305a77aec37a68c107102231faa7a16/pkg/cloud/services/secretsmanager/secret_fetch_script.go#L20
As a result the VMs are not initializing as expected. 
This is workaround until we have a fix available in cloud-init.
* https://d2iq.atlassian.net/browse/D2IQ-99614
Created AMI `ami-0a2a327f0619dff0e` using the downgraded AMI version and was able to create cluster successfully.  …
> fix: downgrade cloud-init package for ubuntu OS 

- ansible/roles/packages/tasks/debian.yaml
- pin cloud-init version to `23.1.2-0ubuntu0~20.04.2` for ubuntu
* https://d2iq.atlassian.net/browse/D2IQ-99614
```release-note
```
> fix: downgrade cloud-init to 23.1.2-0ubuntu0~20.04.2

- ansible/group_vars/all/defaults.yaml
- ansible/roles/packages/tasks/debian.yaml
- images/ami/ubuntu-2004.yaml
This PR adds a `pinned_debs` ansible variable that can be overridden at runtime to provide pinned deb rpms.
It pins cloud-init rpm for ubuntu as it breaks current deployment of CAPA clusters. https://github.com/kubernetes-sigs/image-builder/issues/1333
* https://d2iq.atlassian.net/browse/D2IQ-99614
> fix: install pinned cloud-init for only ubuntu 20.04

- ansible/roles/providers/tasks/googlecompute.yml
- images/gcp/centos-79.yaml
- images/gcp/ubuntu-1804.yaml
- images/gcp/ubuntu-2004.yaml
The system package include a Python interpreter compatible with gcloud.
Ubuntu 18.04 ships a Python interpreter that is not supported by gcloud v448 and newer.
* https://d2iq.atlassian.net/browse/D2IQ-99736
```release-note
```
> fix: Install gcloud CLI system package

- ansible/roles/providers/tasks/googlecompute.yml
- images/gcp/centos-79.yaml
- images/gcp/ubuntu-1804.yaml
- images/gcp/ubuntu-2004.yaml
The system package include a Python interpreter compatible with gcloud.
Ubuntu 18.04 ships a Python interpreter that is not supported by gcloud v448 and newer.
Backport of #967 
```release-note
```
> [release-2.5] fix: Install gcloud CLI system package

- test/infra/vsphere/main.tf
I wanted to use new vSphere templates but the [v2.5.3 build failed](https://github.com/mesosphere/konvoy-image-builder/actions/runs/6673475549)
Backport of https://github.com/mesosphere/konvoy-image-builder/pull/928
See vSphere build working https://github.com/mesosphere/konvoy-image-builder/actions/runs/7331572962
```release-note
```
> [release-2.5] fix: downgrade vsphere version

- cmd/konvoy-image/cmd/vsphere.go
When introducing the vsphere subcommand an copy+paste error for two settings arguments where made.
`ssh-privatekey-file` and `ssh-publickey` to override `resource-pool` instead to assign their config value.
This PR fixes this problem.
Backport PRs will follow up
* https://d2iq.atlassian.net/browse/D2IQ-99862
```release-note
fix: wrong assignment of vsphere arguments `ssh-publickey` and `ssh-privatekey-file` will override resource pool.
```
> fix: wrong vsphere config assignment

- .github/workflows/aws-e2e.yaml
- .github/workflows/azure-e2e.yaml
- .github/workflows/build-devkit-image.yaml
- .github/workflows/gcp-e2e.yaml
- .github/workflows/podman-aws-e2e.yaml
- .github/workflows/release-ami.yaml
- .github/workflows/release-azure.yaml
- .github/workflows/release-gcp-template.yaml
- .github/workflows/release-kib.yaml
- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
- Fix flaky issues with `docker buildx` not coming up, we're bumping the GHA version here.
- Remove `linked_clone` from VSphere tests, this causes the  Ubuntu images to fail. Discussion threads [here](https://nutanix.slack.com/archives/C069QMDB2QM/p1706462776451489), and [here](https://nutanix.slack.com/archives/C069QMDB2QM/p1706546883620639).
- https://d2iq.atlassian.net/browse/D2IQ-99908
```release-note
```
> chore: E2E tooling fixes.

- cmd/konvoy-image/cmd/vsphere.go
Backport of #980 
When introducing the vsphere subcommand an copy+paste error for two settings arguments where made.
`ssh-privatekey-file` and `ssh-publickey` to override `resource-pool` instead to assign their config value.
This PR fixes this problem.
Backport PRs will follow up
* https://d2iq.atlassian.net/browse/D2IQ-99862
```release-note
fix: wrong assignment of vsphere arguments `ssh-publickey` and `ssh-privatekey-file` will override resource pool.
```
> fix: wrong vsphere config assignment - backport 2.5

- ansible/group_vars/all/defaults.yaml
- ansible/group_vars/all/system.yaml
- ansible/roles/repo/tasks/debian.yaml
- images/common.yaml
- Update debian package repositories to use `pkgs.k8s.io`
- Bump critools to v1.28
- https://jira.d2iq.com/browse/D2IQ-99586
- https://jira.d2iq.com/browse/D2IQ-99953
- There was an attempt to template `kubernetes_version` via 
`{{ kubernetes_major }}.{{ kubernetes_minor }}.{{ kubernetes_patch}}` but this fails many tests as the templated version is referenced by the Magefile [here](https://github.com/mesosphere/konvoy-image-builder/blob/8773728fb51a83c985d3d1a6e4fbdbb666c1bf88/magefile.go#L375).
```release-note
```
> fix: Update k8s debian package repositories to pkgs.k8s.io, bumps critools to 1.28 

- ansible/group_vars/all/defaults.yaml
Update contained version to 1.6.28. This resolves CVE-2024-21626. 
https://d2iq.atlassian.net/browse/D2IQ-99943
```release-note
```
> feat: bump Containerd to 1.6.28

- ansible/roles/providers/tasks/aws.yml
Backport of #866 
Flatcar image fails to build in release-2.5. For example, https://github.com/mesosphere/konvoy-image-builder/actions/runs/7980485399/job/21871361341?pr=1011#step:9:2493
```release-note
```
> [release-2.5] [backport] fix: cython issue for flatcar

- ansible/group_vars/all/defaults.yaml
- ansible/group_vars/all/system.yaml
- ansible/roles/repo/tasks/debian.yaml
Updates the package repositories and related metadata. Older repositories are deprecated, and packages for newer 1.26 patch versions are unavailable.
```release-note
```
> [release-2.5] [backport] fix: Update k8s debian package repositories to pkgs.k8s.io

- ansible/group_vars/all/defaults.yaml
- ansible/group_vars/all/system.yaml
- ansible/roles/repo/tasks/debian.yaml
- images/common.yaml
The packages were rebuilt with the correct cri-tools version using https://github.com/mesosphere/dkp-release/pull/119
```release-note
```
> [release-2.8] feat: bump Kubernetes to v1.27.11

- ansible/group_vars/all/defaults.yaml
- ansible/roles/config/templates/config.toml.tmpl
Changes to support provisioning clusters with https://github.com/d2iq-labs/capi-runtime-extensions
1. Loads image `"ghcr.io/mesosphere/dynamic-credential-provider:v0.5.0"` into Containerd. The supported Kubelet APIs changed between `v0.2.0` and `v0.5.0`, and to avoid doing a migration during upgrades just loading both images here.
2. Removing the `docker.io` mirror. This configuration is no longer needed and has been removed from upstream image-builder.
```
Feb 27 05:07:07 ip-10-0-128-224.us-west-2.compute.internal containerd[1624]: time="2024-02-27T05:07:07.812061161Z" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: `mirrors` cannot be set when `config_path` is provided"
```
**Which issue(s) does this …
> fix: minor changes to support CRE

- ansible/group_vars/all/defaults.yaml
- images/common.yaml
The packages were rebuilt with the correct cri-tools version using https://github.com/mesosphere/dkp-release/pull/119
```release-note
```
> [release-2.8][backport] feat: Update kubernetes version to v1.27.11

- ansible/group_vars/all/defaults.yaml
Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1010 to pickup CVE fixes
```release-note
```
> [release-2.8][backport] feat: update Containerd to 1.6.28

- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
Saw a failure with v2.9.4 vSphere [release build job](https://github.com/mesosphere/konvoy-image-builder/actions/runs/8192924748/job/22536461146#step:10:1620)
```
Error: failed to fetch airgap artifacts: failed to fetch OS bundle running "bin/konvoy-image-wrapper create-package-bundle --os=redhat-8.4 --output-directory=artifacts" failed with exit code 1
```
Here is a test run with this fix https://github.com/mesosphere/konvoy-image-builder/actions/runs/8240881511/job/22537114860, its still failing but for a different reason (will have a follow up PR)
```release-note
```
> ci: set RHSM envs when building vSphere templates

- bundles/redhat8.4/packages.txt.gotmpl
- bundles/redhat8.6/packages.txt.gotmpl
- bundles/redhat8.8/packages.txt.gotmpl
- bundles/rocky9.1/packages.txt.gotmpl
These packages may be needed for vSphere templates
* https://d2iq.atlassian.net/browse/D2IQ-100208
Running AWS tests to verify that including these packages doesn't break anything else, the vSphere tests passed in ~https://github.com/mesosphere/konvoy-image-builder/actions/runs/8241197843~ https://github.com/mesosphere/konvoy-image-builder/actions/runs/8250801214
```release-note
```
> fix: include python2-pip package for RHEL

- .github/workflows/release-ami.yaml
Fixes an issue with kommander-e2e tests which was previously using upstream AMIs but is no longer. This should unblock @mhrabovcin https://github.com/mesosphere/kommander-e2e/pull/973
```release-note
```
> fix: adds an ubuntu release for kommander tests

- .github/workflows/release-ami.yaml
Similar to https://github.com/mesosphere/konvoy-image-builder/pull/1041, but for AWS.
Builds working https://github.com/mesosphere/konvoy-image-builder/actions/runs/8253869136
```release-note
```
> ci: set RHSM envs when building AWS AMIs

- magefile.go
- overrides/runtags.yaml
Adds an override to make sure there is an expiration for all ec2 instances spawned.
```release-note
```
> ci: adds expiration tag for e2e runs

- cmd/konvoy-image-wrapper/cmd/wrapper.go
`.aws/config` is being ignored by KIB. This is an issue especially when custom config like `aws configure sso` is being used or special profiles.
Due to the D2iQ tooling relied completely on .aws/credentials this was never noticed before.
* https://jira.nutanix.com/browse/D2IQ-100548
`.aws/config` is an important part of SDK config. We completely forgot about it
No change expected. If the file is not provided or existing its should be ignored
> D2IQ-100548: add missing .aws/config file mount - main

- ansible/roles/repo/tasks/redhat.yaml
- Always clean yum cache after adding kubernetes repositories
Once we add a repo to the yum cache, we need to update the yum caches so that the packages from the repo can be downloaded.
when we install ansible packages we do use `update_cache: yes` option. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-update_cache
however it will clean the cache only if it is expired. So the new packages are not getting downloaded automatically even after ansible invokes update cache.
This PR forces yum to clean all yum caches including repo mirror list so that package list can be refreshed automatically. 
* https://jira.nutanix.com/browse/NCN-100851
> fix: clean yum cache after adding repos 

- ansible/group_vars/all/defaults.yaml
bumps dynamic credentials provider to v0.5.3
> chore: bump dynamic-credential-provider to v0.5.3

- ansible/roles/config/templates/config.toml.tmpl
Spotted this issue again when testing vSphere install/upgrade with Kubernetes v1.29.5.
Similar to https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/645, but solving it here to handle the more generic case of so it can be picked up during upgrades without needing to add complicated `preKubeadmCommands` update logic in Konvoy2.
This enabled pods to run as non-root and bind to privileged ports as long as they have the necessary capability, `CAP_NET_BIND_SERVICE` added.
This fixes an issue on AWS when bringing up coredns which binds to port 53 but runs as an unprivileged user.
Overall this is a net security improvement for clusters, meaning users can stop giving too many privileged to pods - see …
> fix: Enable unprivileged ports sysctl in containerd config

- .github/workflows/podman-aws-e2e.yaml
- cmd/konvoy-image-wrapper/image/image.go
Remove workaround for podman 3.x image load behavior, because the workaround is incompatible with podman 4.x.
Also:
- Use Ubuntu 24.04 runner to run podman e2e test. This runner includes podman 4.x, which we require. 
- Use Rocky 9.1 to run podman e2e test. Previously, we used CentOS 7.9, but we cannot use it, because we dropped support for it recently (#1072), as it went EOL.
* https://jira.nutanix.com/browse/NCN-101343
```release-note
```
> fix: Make image load compatible with podman 4.x

- bundles/redhat8.6/packages.txt.gotmpl
- bundles/redhat8.8/bundle.sh.gotmpl
- bundles/redhat8.8/packages.txt.gotmpl
Updates the default packages we publish for offline builds to be compatible with the latest images of RHEL 8.6 and RHEL 8.8 available from AWS.  It should be noted that a customer's base operating system can use a different base image, so these packages won't necessarily work in every scenario. They are specific to our testing.
```release-note
```
> fix: redhat 8.6 and redhat 8.8 gpu support 

- bundles/redhat8.8/bundle.sh.gotmpl
- bundles/redhat8.8/packages.txt.gotmpl
Adds baseos image repo. This is needed in rhel 8.8 for packages such as audit. We saw this error here on the last run https://github.com/mesosphere/konvoy-image-builder/actions/runs/9883918228/job/27299511067#step:9:1712
```release-note
```
> fix: adds base os repo and kernel package

- bundles/redhat8.6/packages.txt.gotmpl
- bundles/redhat8.8/packages.txt.gotmpl
- cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
- magefile.go
Adds a gate around fetching kernel headers with a note about where to modify the file in the help text of the flag. Also updates CI to use this new flag.
```release-note
```
> ci: fetch kernel headers only for GPU tests

- ansible/group_vars/all/defaults.yaml
- ansible/roles/providers/tasks/misc.yml
set sysctl settings for fs.inotify to same as upstream image builder
*https://jira.nutanix.com/browse/NCN-101967
```release-note
```
> fix: set sysctl settings for fs.inotify 

- ansible/roles/providers/tasks/main.yml
- ansible/roles/providers/tasks/vmware-redhat.yaml
- ansible/roles/providers/tasks/vmware.yml
> [release-2.5] fix: cloud init problems with ubuntu (#1158)

- ansible/roles/packages/tasks/debian.yaml
- ansible/roles/sysprep/tasks/debian.yml
Concurrent runs of apt outside the scope of the ansible playbook, e.g. unattended upgrades, acquire the apt lock. This ensures that we wait (up to a maximum duration) for the lock to be released any time we run apt.
```release-note
```
> fix: Wait for concurrent apt process to release lock

- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
- images/ova/ubuntu-2204.yaml
- magefile.go
Adds support for creating an Ubuntu 22.04 OVA (vSphere) image.
```release-note
```
> feat: Support creating Ubuntu 22.04 OVA (vSphere) image

- ansible/roles/packages/tasks/debian.yaml
- ansible/roles/sysprep/tasks/debian.yml
Backport of #1177
```release-note
```
> [release-2.9] fix: Wait for concurrent apt process to release lock

- ansible/group_vars/all/defaults.yaml
Updates to latest Containerd patch release https://github.com/containerd/containerd/releases/tag/v1.7.22
https://jira.nutanix.com/browse/NCN-102515
```release-note
```
> feat: bump Containerd patch release 1.7.22

- Dockerfile.devkit
- ansible/group_vars/all/defaults.yaml
- cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
- images/common.yaml
bump k8s version to 1.30.5
https://jira.nutanix.com/browse/NCN-102271
```release-note
```
> feat: bump the k8s version

- pkg/packer/manifests/aws/packer.pkr.hcl
Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1124
* https://jira.nutanix.com/browse/NCN-101592
```release-note
```
> [release-2.5] fix: remove snapshot groups (#1124)

- ansible/roles/kubeadm/tasks/redhat.yaml
- enable installing cri-tools from upstream repo.
currently it the cri-tools must be available in Docker image. Enable installing cri-tools for conditions where the cri-tools is not baked in the container image.
> fix: enable installing cri-tools rpm from upstream repo

- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
- images/ova/oracle-94.yaml
- magefile.go
This adds new configuration to build Oracle Linux 9.4 vSphere templates.
* https://jira.nutanix.com/browse/NCN-102630
✅ I built a template [here](https://github.com/mesosphere/konvoy-image-builder/actions/runs/11076002535) and then ran an install test [here](https://github.com/mesosphere/konvoy2/actions/runs/11076450767/job/30779936267#step:5:6702).
Will wait for a PR to support building the air-gapped bundle and then we can run the air-gapped tests there.
```release-note
```
> feat: add Oracle Linux 9.4 vSphere build configuration

- ansible/roles/providers/tasks/main.yml
- ansible/roles/providers/tasks/vmware-redhat.yaml
- ansible/roles/providers/tasks/vmware.yml
Backport of #1150.
Similar to https://github.com/mesosphere/konvoy-image-builder/pull/1173, which was for release-2.5.
```release-note
```
> [release-2.8] fix: cloud init problems with ubuntu (#1150)

- bundles/redhat8.4/repo-templates/centos.repo
- magefile.go
Incorrect Magefile changes were merged when cherry-picking https://github.com/mesosphere/konvoy-image-builder/pull/1133 to `release-2.9` branch.
This PR removes use of the unused flags.
```release-note
```
> fix(release-2.9): remove using undefined flags in magefile

- Makefile
The devkit image is only built and push if its SHA changes. 
When a kubernetes, containerd or crictl-tools versions changed in `ansible/group_vars/all/defaults.yaml` file, the devkit image should be rebuilt.
This change will force rebuilding devkit image.
> build: include changes in defaults.yaml when buiding devkit image

- ansible/group_vars/all/defaults.yaml
With the previous version of the nvidia driver we were seeing an issue with some symbols that we're GPL only. This updates the driver to the latest 470 driver version which avoids that issue
error log below for posterity 
```bash
-> Error.
ERROR: An error occurred while performing the step: "Checking to see whether the nvidia kernel module was successfully built". See /var/log/nvidia-installer.log for details.
-> The command `cd ./kernel; /usr/bin/make -k -j8 NV_KERNEL_MODULES="nvidia" NV_EXCLUDE_KERNEL_MODULES="" SYSSRC="/lib/modules/5.15.0-1070-aws/build" SYSOUT="/lib/modules/5.15.0-1070-aws/build"` failed with the following output:
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-1070-aws'
warning: the compiler differs from the one used …
```
> [release-2.8] fix: bumps nvidia version to a newer one that no longer uses GPL symbols

- ansible/group_vars/all/defaults.yaml
this one but cherry picked to 2.9 https://github.com/mesosphere/konvoy-image-builder/pull/1200
```release-note
```
> [release-2.9] fix: bumps nvidia version to a newer one that no longer uses GPL symbols

- ansible/roles/providers/files/etc/vmware-tools/tools.conf
The default timeout is 30s. At that point, open-vm-tools restarts the machine, interrupting the cloud-init bootstrap; the bootstrap does not run on reboot.
Because kubeadm init/join runs as a cloud-init command, and can run over 5m, the timeout is not enough.
* https://jira.nutanix.com/browse/NCN-103154
```release-note
```
> fix: Allow open-vm-tools to wait indefinitely for cloud-init to finish

- ansible/roles/providers/files/etc/vmware-tools/tools.conf
The default timeout is 30s. At that point, open-vm-tools restarts the machine, interrupting the cloud-init bootstrap; the bootstrap does not run on reboot.
Because kubeadm init/join runs as a cloud-init command, and can run over 5m, the timeout is not enough.
Backport of #1203
* https://jira.nutanix.com/browse/NCN-103154
```release-note
```
> [release-2.14] fix: Allow open-vm-tools to wait indefinitely for cloud-init to finish

- bundles/redhat8.4/bundle.sh.gotmpl
- bundles/redhat8.4/repo-templates/rocky.repo
- bundles/redhat8.4/rocky-appstream.repo
Installing modulemd-tools from Rocky instead of Centos
https://jira.nutanix.com/browse/NCN-103667
n/a, fixing bugs
> [release-2.9] fix: hack to load modulemd-tools for rhel 84

- .github/workflows/azure-e2e.yaml
- .github/workflows/release-azure.yaml
- images/azure/rocky-9.yaml
- magefile.go
Rocky deprecates versions as soon as the next minor is released https://wiki.rockylinux.org/rocky/version/#current-supported-releases.
Dropping the minor version in Azure to avoid referencing a removed image in the future. 
```release-note
```
> fix: use Rocky 9 without a minor version for Azure

- ansible/group_vars/all/system.yaml
The gpg key expired for ubuntu releases in Kubernetes version 1.27.
This bumps where the key gets retrieved so we don't get any fails when building KIB images.
https://jira.nutanix.com/browse/NCN-104032
This would resolve this upstream complication for us:
https://github.com/kubernetes/release/issues/3818
n/a
> [release-2.8] fix: gpg key expired for v1.27

- images/gcp/ubuntu-2004.yaml
Failed gcp runs for Ubuntu 20.04
NCN-104362
Changing the lookup for the gcp image for Ubuntu 20.04
Solely for creating a GCP Ubuntu 20.04 image
> chore: changing gcp image for ubuntu 20.04

- ansible/roles/providers/tasks/aws.yml
- bundles/redhat8.10/packages.txt.gotmpl
pins cloud-init version to the last version that works on AWS without problems 
```release-note
```
> fix: pins cloud init to last known working version for aws 

- .github/workflows/gcp-e2e.yaml
- .github/workflows/release-gcp-template.yaml
- images/gcp/ubuntu-2204.yaml
feat: support ubuntu 22.04 for gcp images
* https://jira.nutanix.com/browse/NCN-104802
> feat: support ubuntu 22.04 for gcp images 

- .github/workflows/aws-e2e.yaml
- .github/workflows/vsphere-e2e.yaml
- bundles/ubuntu22.04/bundle.sh.gotmpl
- bundles/ubuntu22.04/packages.txt.gotmpl
- cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
- Create package bundle for ubuntu-22.04
- ensure that the cloud-init version supported by CAPA is installed. `cloud-init_23.1.2-0ubuntu0~22.04.1_all`  https://github.com/mesosphere/konvoy-image-builder/blob/main/images/ami/ubuntu-2204.yaml#L8
- ensure that latest cloud-init version is installed that is needed for all other providers than CAPA
* https://jira.nutanix.com/browse/NCN-104852
tested manually and GHA e2e tests will verify this. 
ensure that both cloud-init packages are installed.
```
❯ tar -tvf 1.31.4_ubuntu_22.04_x86_64.tar.gz | grep cloud-init
-rw-r--r--  0 501    dialout  530940 Apr 25  2023 cloud-init_23.1.2-0ubuntu0~22.04.1_all.deb
-rw-r--r--  0 501    dialout …
```
> feat: create package bundle for ubuntu 22.04

- Dockerfile.devkit
Previously 4xx and 5xx errors were ignored, which resulted in an invalid devkit image. This then lead to situations where the image was never rebuilt since the same image with that SHA was already in Dockerhub.
```release-note
```
> fix: fail on curl errors in devkit build

- bundles/redhat8.8/README.md
- bundles/redhat8.8/packages.txt.gotmpl
Updates RHEL 8.8 kernel headers version. The previous version is no longer in the repository.
* https://jira.nutanix.com/browse/NCN-105791
```release-note
```
> fix: Update RHEL 8.8 kernel headers version

- bundles/redhat8.10/README.md
Updates RHEL 8.10 kernel headers version. The previous version is no longer in the repository.
* https://jira.nutanix.com/browse/NCN-105791
```release-note
```
> fix: Update RHEL 8.10 kernel packages version

- ansible/roles/config/tasks/main.yaml
- ansible/roles/providers/tasks/misc.yml
Sets sysctl settings for inotify in a common place between preprovisioned and cloud providers. 
*[NCN-105830](https://jira.nutanix.com/browse/NCN-105830)
```release-note
sets sysctl settings for inotify on preprovisioned nodes
```
> fix: moves sysctl settings to a common place for preprovisioned and providers

- .github/workflows/podman-aws-e2e.yaml
- Dockerfile
- Dockerfile.devkit
- Makefile
- ansible/group_vars/all/defaults.yaml
- ansible/roles/images/tasks/main.yaml
- ansible/roles/images/tasks/upload.yaml
- ansible/roles/offline/tasks/upload.yaml
- hack/download-artifacts.sh
- magefile.go
- overrides/offline-fips.yaml
- overrides/offline.yaml
include kuberentes images in the KIB container image. This will help with avoiding rate limited by docker hub.
includes both fips and non-fips images
moved downloading artifacts to the script so that its easier to sync it with NIB
uses included kubernetes images in both airgap and networked installations. 
* https://jira.nutanix.com/browse/NCN-106565
```release-note
```
> feat: download kubernetes images in the KIB container 

- ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py
Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1272
This fixes the linter error. While looking at this, I also noticed that the second log message was using the wrong variable.
```release-note
```
> [release-2.22] fix: custom cloudinit script

- .github/workflows/release-kib.yaml
Since we are adding the k8s images in the binary, the macos signing and notarization during the release job is timing out.
Increasing the runner size to "large" to see if it fixes it.
```release-note
```
> ci: run the release job with large runner

- .github/workflows/release-kib.yaml
Bump runner to large
```release-note
```
> ci(release-2.22): bump GHA runner to large for release workflow

- .github/workflows/release-vsphere-template.yaml
RHEL 8.6 is no longer supported and the builds fail https://github.com/mesosphere/konvoy-image-builder/actions/runs/14040676595/job/39872319392
```release-note
```
> ci: remove RHEL 8.6 from the vSphere release matrix

- pkg/packer/manifests/azure/packer.pkr.hcl
Support passing `source_gallery_name` and `source_gallery_image_name` to use a compute gallery images built from a VHD.
This is useful to build Rocky 9.5 images from source https://dl.rockylinux.org/vault/rocky/9.5/images/x86_64/ instead of waiting for one to be published in the marketplace.
```release-note
```
> feat: support using gallery images in Azure

- .github/workflows/release-vsphere-template.yaml
- .github/workflows/vsphere-e2e.yaml
- test/infra/vcd/bastion.tf
- test/infra/vcd/variables.tf
- test/infra/vsphere/main.tf
- test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
- test/infra/vsphere/packer-vsphere-basic.yaml.tmpl
- test/infra/vsphere/variables.tf
Updates the GHA workflow to use our current vSphere environment to build vSphere images for konvoy e2e tests.
Backport of  #1289
```release-note
```
> ci(release-2.18): run vsphere e2e tests on nkp vcenter

- bundles/redhat8.10/packages.txt.gotmpl
Building Airgapped images for GPU on AWS for RHEL 8.10
https://jira.nutanix.com/browse/NCN-107968
solely bumping kernel versions
n/a
> fix(release-2.22): bump nvidia kernel headers for RHEL 8.10

- bundles/redhat8.8/packages.txt.gotmpl
Building Airgapped images for GPU on AWS for RHEL 8.8
https://jira.nutanix.com/browse/NCN-107970
solely bumping kernel versions
n/a
> fix(release-2.22): bump nvidia kernel headers for RHEL 8.8

- bundles/redhat8.10/packages.txt.gotmpl
Update kernel header version to `kernel-headers-4.18.0-553.60.1.el8_10` 
```release-note
```
> fix: update kernel header versions for rhel-8.10

- ansible/roles/providers/tasks/misc.yml
on azure rocky builds cloud init fails because there is no datasource called EC2Kubernetes, which gets added because of this file.we should just run this file for AWS 
```shell
[  OK  ] Started User Login Management.
[   14.847463] cloud-init[925]: [2025-07-30 21:12:27] Cloud-init v. 24.4-4.el9.0.1 running 'init-local' at Wed, 30 Jul 2025 21:12:27 +0000. Up 14.22 seconds.
[  OK  ] Finished Cloud-init: Local Stage (pre-network).
[   14.867461] cloud-init[925]: [2025-07-30 21:12:28] 2025-07-30 21:12:28,282 - sources[ERROR]: Could not import DataSourceEc2Kubernetes. Does the DataSource exist and is it importable?
[  OK  ] Reached target Preparation for Network.
Starting Network Manager...
Starting Hostname Service...
[  OK  ] Started Hostname Service. …
```
> fix: only use Ec2Kubernetes datasource in aws

- ansible/roles/packages/tasks/debian.yaml
- ansible/roles/repo/tasks/debian-offline.yaml
This attempts to fix the problem where we can't install items from the offline repository as seen here:
https://github.com/mesosphere/konvoy-image-builder/actions/runs/17097491616/job/48820722266#step:9:2826
```
amazon-ebs.kib_image: fatal: [default]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to update apt cache: unknown reason"}
```
this updates the cache as soon as we start using the offline repository. strangely, this error is not occurring on the main builds despite using the same AMI 
```release-note
```
> fix: update cache after adding offline repository
