docs/nvidia-gpu.md

Help for that command:
```
[...]
--overrides stringArray            a list of override YAML files
[...]
```

chore: fixed typo in example

---

ansible/roles/networking/files/host.conf
ansible/roles/networking/tasks/files/etc-hosts.flatcar.noipv6
ansible/roles/networking/tasks/main.yaml
cmd/konvoy-image/cmd/args.go
cmd/konvoy-image/cmd/generate.go
cmd/konvoy-image/cmd/provision.go
images/generic/centos-7.yaml
images/generic/centos-8.yaml
images/generic/flatcar.yaml
images/generic/sles-15.yaml
pkg/app/build.go
pkg/app/provision.go

This PR is based flatcar-stable which contains some required work for gpu support. The feature branch for gpu support has diverged and I will work on rebasing and getting that feature merged before merging flatcar-stable into main.
Head of jr/flatcar-provision has been tagged v1.0.0-rc.2

Flatcar Preprovision Support

---

ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
cmd/konvoy-image-wrapper/cmd/wrapper.go
docs/cli/konvoy-image_provision.md
pkg/app/build.go
pkg/appansible/io.go

Fixing errors introduced by https://github.com/mesosphere/konvoy-image-builder/pull/57

fix: lint errors

---

cmd/konvoy-image/cmd/generate.go

fixes https://jira.d2iq.com/browse/D2IQ-78097

bug: fix overrides

---

ansible/group_vars/all/system.yaml
ansible/roles/gpu/defaults/main.yaml

https://jira.d2iq.com/browse/D2IQ-79232

feat: Upgrade NVIDIA GPU drivers to 470.x 

---

ansible/group_vars/all/system.yaml
ansible/roles/config/tasks/main.yaml
ansible/roles/packages/tasks/install-debian.yaml
ansible/roles/packages/tasks/install.yaml
ansible/roles/packages/tasks/repo-debian.yaml
ansible/roles/packages/tasks/repo.yaml
ansible/roles/providers/tasks/aws.yml
goss/ubuntu/kernel-params.yaml
goss/ubuntu/packages.yaml
goss/ubuntu/services.yaml
images/ami/ubuntu-20.yaml
images/ami/ubuntu-focal.yaml
images/generic/ubuntu-20.yaml

ubuntu 20.04

---

Makefile
ansible/molecule/ec2_full/molecule.yml
ansible/molecule/ec2_gpu/molecule.yml
ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml
ansible/roles/gpu/tasks/nvidia-gpu.yaml
ansible/roles/validate/tasks/main.yaml

https://jira.d2iq.com/browse/D2IQ-79489

Ubuntu 20.04 LTS Nvidia GPU support. 

---

ansible/roles/packages/tasks/install.yaml
ansible/roles/packages/templates/config.toml.tmpl

align with upstream, proposed import path:
https://github.com/kubernetes-sigs/image-builder/pull/711/files#diff-d1af58ebd853b2f1c14f31e9f5675982297b4584d28fdef0845bd07c9083a9b7R109

update include directory to align with upstream

---

.gitignore
Makefile
ansible/roles/packages/handlers/main.yaml
ansible/roles/packages/tasks/install-redhat.yaml
ansible/roles/validate/tasks/main.yaml
goss/oracle/kernel-params.yaml
goss/oracle/packages.yaml
goss/oracle/services.yaml
images/ami/oracle-7.yaml
images/ami/oracle-8.yaml
images/generic/oracle-7.yaml
images/generic/oracle-8.yaml

- Add Oracle Linux 7/8 as an image target
- Add Oracle Linux 7/8 to CI builds

Images: Add Oracle Linux 7/8

---

ansible/group_vars/all/defaults.yaml
ansible/group_vars/all/system.yaml
ansible/roles/images/defaults/main.yaml
overrides/fips.yaml

```
TASK [images : pull control plane images] **************************************
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=mesosphere/kube-apiserver:v1.21.6_fips.0)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=mesosphere/kube-controller-manager:v1.21.6_fips.0)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=mesosphere/kube-scheduler:v1.21.6_fips.0)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=mesosphere/kube-proxy:v1.21.6_fips.0)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=mesosphere/etcd:v3.4.13_fips.0)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => (item=k8s.gcr.io/pause:3.4.1)
changed: [ec2-35-86-165-237.us-west-2.compute.amazonaws.com] => …
```

allow overriding image repository and tags

---

.github/pull_request_template.md

Adds a PR template for clearer PRs

chore: adds pr template

---

Dockerfile
Dockerfile.devkit
ansible/_validate.yaml
ansible/roles/validate/tasks/main.yaml
ansible/validate.yaml

- Install netaddr in container to enable inventory IP address validation
```log
> bin/konvoy-image-wrapper validate
PLAY [Check Machine Readiness] *************************************************
TASK [Gathering Facts] *********************************************************
ok: [54.189.71.76]
TASK [validate : check for supported OS] ***************************************
ok: [54.189.71.76]
TASK [validate : check memory swap is disabled] ********************************
ok: [54.189.71.76]
TASK [validate : check hostnames are unique] ***********************************
ok: [54.189.71.76]
TASK [validate : check node IPs do not overlap with serviceSubnet] *************
fatal: [54.189.71.76]: FAILED! => {"msg": "The conditional check …
```

Fixes to validate command

---

Makefile

When a non-static binary is built on a distro with a newer glibc, it fails to execute in the older devkit distro. Make static binaries always.
```release-note
```

Always build a static binary

---

hack/os-packages/Makefile

These packages were missing when using a minimal OS.
```release-note
```

fix: add missing RPMs needed for CentOS 7 minimal

---

ansible/roles/offline/tasks/upload.yaml

While testing with John and Dan, we noticed that even when an updated tar is uploaded and unarchived.
Sample output of this running.
I ran an install with one OS package bundle, the reran with a different OS package bundle.
Notice that the outdated directory was removed and unarchived again
```
TASK [offline : create offline OS packages directory] **************************
ok: [54.218.105.67]
TASK [offline : upload OS packages bundle to remote] ***************************
changed: [54.218.105.67]
TASK [offline : remove outdated os packages] ***********************************
changed: [54.218.105.67]
TASK [offline : create offline OS packages directory after cleanup] ************
changed: [54.218.105.67]
TASK [offline : unarchive OS packages bundle …
```

feat: remove outdated packages and unarchive again on changes

---

goss/oracle/services.yaml

Makes sure oracle firewalld and iptables services are off
```release-note
```

test: add goss checks to make sure iptables and firewalld are off

---

.github/workflows/conventional-label.yaml
.github/workflows/release-main.yml
.pre-commit-config.yaml

build: add actions to support continuous release automation

---

.github/release.yaml
.github/workflows/conventional-label.yaml
.github/workflows/release-main.yml
.pre-commit-config.yaml

Adds github actions to facilitate a more continuous-release-like process.
```release-note
```

ci: add actions to support continuous release automation

---

Makefile
overrides/fips.yaml

Added Makefile changes and e2e test for RHEL 8.2 FIPS.
```release-note
```

feat: rhel82 FIPS

---

go.mod

fix: add testify to go.mod

---

.github/linters/.markdown-lint.yml
.github/linters/.textlint-whitelist.yaml
.markdown-lint.yml
.textlint-whitelist.yaml
.textlintrc
CHANGELOG.md

The `CHANGELOG.md` needed some linting config to pass by default.
```release-note
```

fix(lint): fix linting errors by configuration

---

README.md
docs/dev/README.md
docs/dev/add-new-os.md
docs/dev/nvidia-gpu.md
docs/dev/vsphere.md

I noticed that there were links that were broken in the dev docs, and just sort of dove a little deeper here and made some more grammar changes and small nits for that.
n/a
All md/readme files
solely documentation.

docs: nits on grammar and fixing links

---

Makefile

feat: added centos79-fips

---

.github/super-linter.env
go.mod
go.sum

fix: go-mod tidy

---

ansible/roles/containerd/tasks/redhat.yaml
ansible/roles/containerd/tasks/suse.yaml
ansible/roles/kubeadm/tasks/redhat.yaml
ansible/roles/packages/tasks/redhat.yaml
ansible/roles/packages/tasks/suse.yaml
ansible/roles/setup_versionlock/tasks/redhat.yaml
ansible/roles/setup_versionlock/tasks/suse.yaml

fix version lock issue to use a fact instead of a local register
```release-note
```

fix: fixes version lock to set fact

---

pkg/packer/manifests/azure/packer.json.tmpl

Found a typo I introduced in #271 while working on getting ubuntu images for azure.
```release-note
```

fix(packer): fix spacing typo in packer template

---

goss/goss.yaml
images/azure/flatcar.yaml
images/azure/oracle-7.yaml
images/azure/oracle-8.yaml
images/azure/rhel-7.yaml
images/azure/rhel-8.yaml
images/azure/sles-15.yaml

Adds additional platforms for azure.
* https://jira.d2iq.com/browse/D2IQ-85256
```release-note
```

feat(azure): add additional images

---

ansible/roles/containerd/tasks/flatcar.yaml
ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
images/ami/flatcar.yaml

fix: support flatcar 3033.2.0

---

.github/workflows/golangci-lint.yml
.github/workflows/lint.yml
go.mod

build: bump golangci-lint

---

Makefile

... also linter fix
Warn about a hidden undocumented environment variable.
```release-note
```

build: warn the developer if BUILD_DRY_RUN is true

---

pkg/packer/manifests/vsphere/base/README.md
pkg/packer/manifests/vsphere/base/packer-base.json
pkg/packer/manifests/vsphere/base/vsphere-base.json

- documents steps needed to create base OS vSphere template
```release-note
```

docs: document steps to create base OS image from DVD ISO

---

ansible/molecule/ec2_gpu/converge.yaml
ansible/provision.yaml

Found this empty file while reviewing the ansible playbook
```release-note
```

chore(ansible): remove unused file

---

ansible/roles/gpu/defaults/main.yaml
ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml

Nvidia has updated and rotated their signing keys: https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
```release-note
```

chore(nvidia): update repo signing keys

---

.goreleaser.yml

Release failure https://github.com/mesosphere/konvoy-image-builder/runs/6394485141?check_suite_focus=true
```release-note
```

ci: include required files in Goreleaser extra_files

---

README.md

release-please doesn't trigger a release for non user facing changes :(
Fixing the README with a `fix` so we get a patch release.
```release-note
```

fix: README remove old  test status

---

.github/workflows/release-main.yml

Whenever KIB releases we should bump CAPPP as well
* 
```release-note
```

ci: adds a kib bump to CAPPP

---

.github/workflows/release-main.yml

Defines outputs for the release please step.
```release-note
```

fix: set outputs from release please

---

cmd/konvoy-image/cmd/build.go
cmd/konvoy-image/cmd/gcp.go

This is the first part of allowing image building for gcp. This sets up the cli to do this, nothing more, I will be building on this as we go and for now it will remain hidden. 
* https://jira.d2iq.com/browse/D2IQ-88880
```release-note
```

[D2IQ-88880] feat: adding skeleton for gcp command to build images (hidden)

---

.github/workflows/release-main.yml

fixes release please configuration for the cappp bump 
```release-note
```

fix: set token param correctly

---

.github/workflows/build.yml
.github/workflows/release-main.yml

uses the correct token for cloning. tested it with the previous commit.
```release-note
```

ci: use correct token for cloning

---

.github/workflows/release-main.yml

Fixed an inconsistent CI Token name
```release-note
```

Replaced CI Tokens with standardized name

---

images/ova/rhel-79.yaml
images/ova/rhel-84.yaml

chore: change vsphere datastore to local disks

---

cmd/konvoy-image/cmd/artifacts.go

Caught when running kovnoy2 repo.
In the future this repo also needs to test this command.
```release-note
```

fix: upload command flag

---

ansible/group_vars/all/defaults.yaml
images/common.yaml
test/e2e/ansible/testdata/ansible/roles/echo/tasks/main.yaml

Bump k8s version to 1.23.7
* https://jira.d2iq.com/browse/D2IQ-90426
```release-note
Update Kubernetes version to v1.23.7
```

feat: bump versions of k8s to 1.23.7

---

.github/workflows/scorecards.yml

Enabled scorecards using GitHub Action. 
https://github.com/ossf/scorecard-action/blob/main/README.md
* https://jira.d2iq.com/browse/[D2IQ-88112](https://jira.d2iq.com/browse/D2IQ-88112)
```release-note
```

Enabled scorecards

---

.github/workflows/release-main.yml
gon.hcl

adding a zip should notarize the file now also avoids a mistake in the release name.
```release-note
```

fix: gon release fixes

---

.github/workflows/release-main.yml

For now, let's hard code to fix until we get #422 in a better state. 
```release-note
```

fix: always use fix for CAPPP bumps

---

.github/workflows/release-tag.yaml

This fix should allow us to run the jobs on tags properly now 
```release-note
```

fix: fix ref in release tag ci

---

gon.hcl

makes gon.hcl work for binary signing 
```release-note
```

fix: gon.hcl for binary signing

---

.github/workflows/release-tag.yaml
gon.hcl

Fixes the final issues with mac notarization 
```release-note
```

fix: notarization and upload fixes

---

ansible/roles/sysprep/tasks/main.yml

https://jira.d2iq.com/browse/D2IQ-92459
```release-note
```

fix: remove builder user in sysprep

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

- Upgrades kubernetes version to 1.24.4
```release-note
Bump default kubernetes version to 1.24.4
```

feat: bump kubernetes version to 1.24.4

---

ansible/roles/sysprep/tasks/main.yml

Reverts mesosphere/konvoy-image-builder#469

feat: disable password ssh auth

---

ansible/roles/sysprep/tasks/main.yml

backports https://github.com/mesosphere/konvoy-image-builder/pull/474
```release-note
```

backport: disable password ssh auth (#474)

---

ansible/roles/sysprep/tasks/main.yml

This reverts commit 60342685a8ef5dc46f8bd152255403e18655176c.
```release-note
```

revert "feat: disable password auth (#490)"

---

.github/workflows/lint.yml

fix: disable unnecessary linters 

---

ansible/group_vars/all/defaults.yaml
ansible/roles/images/tasks/main.yaml

feat: Add toml-merge image for containerd supplementary images

---

.github/workflows/sync-cli-docs.yaml

Updates Confluence pages in the product docs whenever the Markdown files in `docs/cli` change.
* https://d2iq.atlassian.net/browse/D2IQ-91790
```release-note
```

build: sync CLI docs to Confluence

---

README.md

Release-As: 1.24.1
Attempting to fix the release version
https://github.com/googleapis/release-please#how-do-i-change-the-version-number
```release-note
```

chore: release 1.24.1 (see PR description)

---

pkg/packer/manifests/aws/packer.json.tmpl
pkg/packer/manifests/azure/packer.json.tmpl
pkg/packer/manifests/gcp/packer.json.tmpl
pkg/packer/manifests/vsphere/packer.json.tmpl

Backports https://github.com/mesosphere/konvoy-image-builder/pull/559 to release-1.17

[release-1.17][BACKPORT]: fix: Can not specify custom Packer directory #559

---

pkg/packer/manifests/aws/packer.json.tmpl
pkg/packer/manifests/azure/packer.json.tmpl
pkg/packer/manifests/gcp/packer.json.tmpl
pkg/packer/manifests/vsphere/packer.json.tmpl

Backports https://github.com/mesosphere/konvoy-image-builder/pull/559 to release-1.19

[release-1.19][BACKPORT]: fix: Can not specify custom Packer directory #559

---

Dockerfile.devkit

should fix the release job  
```release-note
```

fix: use old add user command

---

images/ami/centos-79.yaml

* https://d2iq.atlassian.net/browse/D2IQ-94286
```release-note
```

fix: use new centos 7.9 base AMI

---

make/images.mk

adds a fips target for oracle 7
```release-note
```

fix: add oracle7 fips target

---

images/ami/centos-79.yaml

backport #573 
```release-note
```

fix: use upstream centos 7

---

ansible/group_vars/all/defaults.yaml
ansible/roles/version/tasks/main.yaml
ansible/roles/version/templates/kubeadm-conf.yaml.tmpl
images/common.yaml

- upgrade kubernetes version to 1.25.4
- Change k8s registry referene to registry.k8s.io
* https://d2iq.atlassian.net/browse/D2IQ-93976
* https://d2iq.atlassian.net/browse/D2IQ-93970
* https://d2iq.atlassian.net/browse/D2IQ-94001
Output from debugging locally.
```
rhel-8.6: TASK [images : print images] ***************************************************
rhel-8.6: ok: [default] => (item=registry.k8s.io/kube-apiserver:v1.25.4) => {
rhel-8.6:     "msg": "registry.k8s.io/kube-apiserver:v1.25.4 image"
rhel-8.6: }
rhel-8.6: ok: [default] => (item=registry.k8s.io/kube-controller-manager:v1.25.4) => {
rhel-8.6:     "msg": "registry.k8s.io/kube-controller-manager:v1.25.4 image" …
```

feat: upgrade kubernetes version to 1.25.4

---

docs/dev/changing-amis.md

Just adding some more flavor/instructions for how to locate and put in a customized source_ami
* https://jira.d2iq.com/browse/D2IQ-94270
solely documentation
solely documentation

docs: adding bit about custom amis

---

pkg/packer/packer.go

propogates signal so we can safely clean up cloud resources
```release-note
```

fix: propogate signals to packer sub-command

---

cmd/konvoy-image-wrapper/cmd/wrapper.go

- remove mounting host user's home directory on container to reduce security risk
- mount credentials and ssh file mounts as readonly
* https://d2iq.atlassian.net/browse/D2IQ-93781
```release-note
```

fix: remove host user's home directory mount from the KIB wrapper container 

---

ansible/roles/networking/tasks/main.yaml

backport #598 to 1.24
```release-note
```

fix: dont ipv6 forward if you dont have ipv6 forwarding file  (#598)

---

ansible/roles/images/tasks/check-or-pull-images.yaml

Found an issue when testing FIPS upgrade.
```release-note
```

fix: retag coredns image with k8s.gcr.io/coredns

---

hack/release.sh

fixes the release script. 
```release-note
```

[skip ci] ci: fixes release script

---

hack/release.sh

when push is true we want to upload the artifacts 
```release-note
```

[skip ci] ci: upload artifacts when push is true

---

Makefile

[skip ci] ci: add buildx dep for devkit-arm64

---

.gitignore

adds files to gitignore 
```release-note
```

[skip ci] ci: add files to gitignore for release

---

images/ami/oracle-79.yaml

failing oracle 7.9 builds 
```release-note
```

fix: use new oracle 7.9 ami

---

ansible/roles/config/templates/config.toml.tmpl

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/644
```release-note
```

fix: configure containerd runc plugin for nvidia

---

ansible/roles/providers/tasks/vmware.yml
ansible/roles/sysprep/tasks/redhat.yml
images/ova/rocky-91.yaml
make/ci.mk
make/images.mk
pkg/packer/manifests/vsphere/packer.pkr.hcl

- build rocky linux 9.1 vsphere template
* https://d2iq.atlassian.net/browse/D2IQ-95242
The rockylinux base template is created using packer HCL template. https://github.com/mesosphere/konvoy-image-builder/compare/shalin/vsphere-rocky-base 
This work still needs some polishing. I will file separate PR for this later because this reference implementation is not blocking.

feat: build vsphere template for rockylinux 9.1

---

images/ova/ubuntu-2004.yaml

adds ubuntu images definition 
```release-note
```

feat: add images file for ubuntu 20.04

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/vsphere-e2e.yaml
Makefile

- [set provenance=false according to](https://github.com/mesosphere/konvoy-image-builder/pull/662/commits/6889805ab0daa635aa1b6485cac4419bd4735e4e) https://github.com/docker/buildx/issues/1509
- blocks GHA until `runs-e2e-tests` label is applied 
```release-note
```

ci: adds some checks for existing files

---

.github/workflows/azure-e2e.yaml

- Add ubuntu 18.04 and rocky 9.1 e2e tests for azure.
```release-note
```

ci: add rocky 9.1 builds configuration for azure

---

ansible/group_vars/all/defaults.yaml

As we have a few more fixes and changes to the offline bundles that will require rebuilding FIPS manifests, this is a good opportunity to update Containerd.
```release-note
```

feat: update Containerd to 1.6.17

---

Makefile

ci: remove deprecated comments from Makefile

---

.github/workflows/release-vsphere-template.yaml
.github/workflows/vsphere-e2e.yaml
test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl

- use new datastore for kib vsphere e2e tests and template generation
- use repository level secret for datastore so that it can be changed dynamically.
Started test: https://github.com/mesosphere/konvoy-image-builder/actions/runs/4246972236/

ci: generate vSphere template on new datastore

---

ansible/group_vars/all/defaults.yaml
ansible/provision.yaml
ansible/roles/containerd/tasks/install.yaml
ansible/roles/gpu/tasks/nvidia-gpu.yaml
ansible/roles/kubeadm/tasks/flatcar.yaml
ansible/roles/packages/tasks/crictl-url.yaml
ansible/roles/packages/tasks/url.yaml
ansible/roles/providers/tasks/googlecompute.yml
ansible/roles/setup_versionlock/tasks/redhat.yaml

https://d2iq.atlassian.net/browse/D2IQ-95908
* https://d2iq.atlassian.net/browse/D2IQ-95908
```release-note
fix: forces all items that use get_url to be downloaded 
```

fix: set force = true and update k8s http source

---

.github/workflows/aws-e2e.yaml

cleans up subnets and vpcs on failure
```release-note
```

ci: delete infra always

---

.github/workflows/release-kib.yaml
.goreleaser.yml
Makefile

Fixes the release 
```release-note
```

Faiq/fix release 1.24

---

ansible/roles/repo/tasks/redhat.yaml

https://d2iq.atlassian.net/browse/D2IQ-96139
```
amazon-ebs.kib_image: TASK [repo : RHEL subscription using username and password] ********************
amazon-ebs.kib_image: skipping: [default]
amazon-ebs.kib_image:
amazon-ebs.kib_image: TASK [repo : RHEL subscription using org_id and activationkey] *****************
amazon-ebs.kib_image: skipping: [default]
amazon-ebs.kib_image:
amazon-ebs.kib_image: TASK [repo : Warning for missing repos] ****************************************
amazon-ebs.kib_image: ok: [default] => {
amazon-ebs.kib_image:     "msg": "WARN: Your system is not using subscription manager fetching packages such as …
```

fix: skip subscribing

---

images/ami/flatcar.yaml

Uses 3033.3.7 LTS flatcar which we support 
```release-note
```

ci: update flatcar to use lts

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/gcp-e2e.yaml
.github/workflows/vsphere-e2e.yaml

Adds labels for each provider in case we have an infra specific test to run 
```release-note
```

ci: adds conditions per provider

---

ansible/roles/providers/tasks/azure-redhat.yml
pkg/packer/manifests/azure/packer.pkr.hcl

This deletes the extra 4 and 5 partitions on azure. We need to explore alternatives to this hard coded approach 
```release-note
```

fix: uses 80gb for all azure builds and removes extra

---

hack/vsphere/main.tf
images/ova/rhel-79.yaml
images/ova/rhel-84.yaml
images/ova/rhel-86.yaml
images/ova/rocky-91.yaml
images/ova/ubuntu-2004.yaml
test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl

update defaults to create kib bastion host to reflect current vSphere infrastrure

ci: update vsphere base template defaults

---

hack/vsphere/main.tf
images/ova/rhel-79.yaml
images/ova/rhel-84.yaml

* ci: update vsphere bastion base template defaults
* fix: change location of base template
* fix: use OS qualification templates for KIB e2e tests
* fix: ubuntu template
---------
```release-note
```

[backport  1.19] ci: update vsphere base template defaults (#752)

---

images/ova/rhel-79.yaml
images/ova/rhel-84.yaml

fix: merge conflicts

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Updates kubernetes version to the latest released version. Also updates crictl CLI version to the latest (as directed in comments in defaults.yaml)
* https://d2iq.atlassian.net/browse/D2IQ-96260
```release-note
```

Upgrade kubernetes version to 1.26.3

---

pkg/app/build.go
pkg/app/config.go
pkg/packer/manifest.go

We are no longer using Go templating with HCL, removing this dead code to further discourage that use.
```release-note
```

chore: remove unused HCL templating code 

---

images/ami/oracle-79.yaml

updates oracle ami file
* https://d2iq.atlassian.net/browse/D2IQ-96605
```release-note
```

fix: new oracle

---

ansible/roles/repo/defaults/main.yaml
ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
ansible/roles/repo/tasks/redhat.yaml
images/common.yaml

We are facing flakiness when installing the epel repo 
```release-note
Retry epel yum repo install up to 30s
```

fix: install epel repo in RHEL 7 using static repo file 

---

ansible/roles/containerd/tasks/suse.yaml

Adds apparmor abstractions package which allows the upgrade control-plane command to return successfully
* https://d2iq.atlassian.net/browse/D2IQ-96645
```release-note
```

fix: adds missing package to address sles issue

---

ansible/roles/containerd/tasks/suse.yaml

Adds apparmor abstractions package which allows the upgrade control-plane command to return successfully 
* https://d2iq.atlassian.net/browse/D2IQ-96645
```release-note
```

fix: adds apparmor abstractions

---

.github/workflows/podman-aws-e2e.yaml
.goreleaser.yml
Dockerfile
Makefile
cmd/konvoy-image-wrapper/cmd/wrapper.go
cmd/konvoy-image-wrapper/image/common.go
cmd/konvoy-image-wrapper/image/image.go
cmd/konvoy-image-wrapper/image/image_not_embedded.go

backport of https://github.com/mesosphere/konvoy-image-builder/pull/789

feat: podman as a supported container engine

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Updates crictl to 1.26.0
* https://d2iq.atlassian.net/browse/D2IQ-96607
```release-note
```

feat: Upgrade kubernetes version to v1.26.6 and CRI tools

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/build.yml
.github/workflows/conventional-label.yaml
.github/workflows/gcp-e2e.yaml
.github/workflows/lint.yml
.github/workflows/release-ami.yaml
.github/workflows/release-kib.yaml
.github/workflows/release-main.yml
.github/workflows/scorecards.yml
.github/workflows/sync-cli-docs.yaml
.github/workflows/vsphere-e2e.yaml

fix: backport CI changes in release-1.24

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/build.yml
.github/workflows/conventional-label.yaml
.github/workflows/gcp-e2e.yaml
.github/workflows/lint.yml
.github/workflows/next-release-version.yml
.github/workflows/release-ami.yaml
.github/workflows/release-azure.yaml
.github/workflows/release-gcp-template.yaml
.github/workflows/release-kib.yaml
.github/workflows/release-vsphere-template.yaml
.github/workflows/scorecards.yml
.github/workflows/sync-cli-docs.yaml
.github/workflows/unit-test.yml
.github/workflows/vsphere-e2e.yaml
.golangci.yml

fix: backport CI changes in release-2.2

---

ansible/roles/repo/defaults/main.yaml
ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
ansible/roles/repo/tasks/redhat.yaml
images/common.yaml

Fixes flakiness when installing EPEL release.
* https://d2iq.atlassian.net/browse/D2IQ-97377
```release-note
```

fix: install epel repo in RHEL 7 using static repo file  (#781)

---

.github/workflows/release-vsphere-template.yaml
requirements-devkit.txt

Needed to fix a build error https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources/76721835#76721835
```release-note
```

build: RHEL8.6 OVA template at release

---

Dockerfile.devkit
ansible/roles/sysprep/tasks/redhat.yml
pkg/packer/manifests/aws/packer.pkr.hcl
pkg/packer/manifests/azure/packer.pkr.hcl
pkg/packer/manifests/gcp/packer.pkr.hcl
pkg/packer/manifests/vsphere/packer.pkr.hcl
requirements-devkit.txt

bumps the ansible packer version so we can remove the SSH Extra Args. 
Also includes a fix for a conditional check that unsubscribes the rhel system. Previously, if the system was not registered this would fail.
```release-note
```

fix: bumps ansible to remove unneeded ssh arguments

---

ansible/roles/providers/tasks/aws.yml

fix: aws cli issue  flatcar

---

requirements-devkit.txt

https://stackoverflow.com/a/76721835
```release-note
```

[release-2.2] build: fix pip build error

---

.gitignore
pkg/packer/manifests/aws/packer.pkr.hcl
pkg/packer/manifests/azure/packer.pkr.hcl
pkg/packer/manifests/gcp/packer.pkr.hcl
pkg/packer/manifests/vsphere/packer.pkr.hcl

[release-2.2] fix: update scp extra args 

---

.github/workflows/release-ami.yaml
images/ami/flatcar.yaml

"Stable" was left over from before, `3033.3.x` is the LTS version.
* https://d2iq.atlassian.net/browse/D2IQ-98869
```release-note
```

build: Flatcar AMI

---

images/ova/rhel-88.yaml

The konvoy e2e failed https://github.com/mesosphere/konvoy2/actions/runs/6168582477/job/16741333433#step:5:4039, the template was built with a wrong name https://github.com/mesosphere/konvoy-image-builder/actions/runs/6162336036/job/16723583671#step:10:3486
```release-note
```

fix: RHEL 8.8 distribution_version

---

images/ova/rhel-88.yaml

fix: RHEL 8.8 build_name

---

test/infra/vsphere/variables.tf

fix: use d2iq base templates

---

magefile.go

- Directly downloads pip packages from downloads.d2iq.com
- refactor the magefile code to download airgap artifacts

chore: download pip packages from downloads.d2iq.com 

---

pkg/packer/manifests/vsphere/packer.pkr.hcl
test/infra/vsphere/main.tf

fixes vsphere packer provider issue by pinning to an older version
```release-note
```

fix: downgrade vsphere version

---

.github/workflows/podman-aws-e2e.yaml
.goreleaser.yml
Makefile
cmd/konvoy-image-wrapper/image/image.go
cmd/konvoy-image-wrapper/image/image_not_embedded.go

fix: use bin/konvoy-image-wrapper now to fix podman tests 

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

feat: upgrade Kubernetes to 1.27.6

---

test/infra/vcd/bastion.tf

Another change similar to https://github.com/mesosphere/konvoy-image-builder/pull/928 but copying VCD vapss.
See successful runs https://github.com/mesosphere/konvoy-image-builder/actions/runs/6563460556
```release-note
```

build: fix VCD terraform version

---

.github/workflows/aws-e2e.yaml
.github/workflows/release-ami.yaml
magefile.go
overrides/fips-configure.yaml

test: adds a fips kernel test

---

cmd/konvoy-image-wrapper/cmd/wrapper.go
pkg/app/config.go

PRs are currently failing the goleaks linter check. The goleaks linter runs as part of super-linter GHA workflow.
```release-note
```

fix: Add directives to false positives reported by goleaks linter

---

cmd/konvoy-image-wrapper/cmd/wrapper.go
pkg/app/config.go

The goleaks linter runs as part of super-linter.
Backport of #968 
```release-note
```

[release-2.5] fix: Add directives to false positives reported by goleaks linter

---

images/ami/sles-15.yaml

* https://d2iq.atlassian.net/browse/D2IQ-99759
```release-note
```

fix: bumps sles to sp5

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Use 1.28.5 k8s version
* https://d2iq.atlassian.net/browse/D2IQ-96260
```release-note
```

feat: use 1.28.5 k8s version

---

images/ami/sles-15.yaml

The SP3 AMI is no longer available.
Backport of #966
```release-note
```

[release-2.5] [backport] Update SLES 15 from SP3 to SP5

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Bump k8s version to latest 1.28.7
https://d2iq.atlassian.net/browse/D2IQ-99578
```release-note
```

feat(k8s): Bump to 1.28.7

---

ansible/group_vars/all/defaults.yaml

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1010 to pickup CVE fixes
```release-note
```

[release-2.5] feat: update Containerd to 1.6.28

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

We need to update etcd to address a bug seen by at least one customer. At the same time, we should update Kubernetes patch version to the latest available.
* https://d2iq.atlassian.net/browse/D2IQ-99879
```release-note
Update Kubernetes to v1.26.14, and etcd to v3.5.10.
```

[release-2.5] feat: Update kubernetes version to v1.26.14

---

magefile.go

e2e: remove problematic p2 instance

---

ansible/group_vars/all/defaults.yaml

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1010 to pickup CVE fixes
```release-note
```

[release-2.8] feat: update Containerd to 1.6.28

---

test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl

[backport-2.5] [release-2.5] ci: Set linked_clone to false during tests

---

Dockerfile.devkit

Updates packer to latest available version.
* https://d2iq.atlassian.net/browse/D2IQ-100094
```release-note
```

fix: update Packer to v1.10.1

---

bundles/centos7.9/bundle.sh.gotmpl
bundles/redhat8.4/bundle.sh.gotmpl
bundles/redhat8.6/bundle.sh.gotmpl
bundles/redhat8.8/bundle.sh.gotmpl
bundles/rocky9.1/bundle.sh.gotmpl

fix: Configure yum to return an error on missing package

---

ansible/group_vars/all/defaults.yaml
ansible/group_vars/all/system.yaml
ansible/roles/repo/tasks/debian.yaml

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/996
* https://d2iq.atlassian.net/browse/D2IQ-100167
```release-note
```

[release-2.8][backport] fix: Update k8s debian package repositories to pkgs.k8s.io

---

bundles/redhat7.9/bundle.sh.gotmpl
bundles/redhat7.9/packages.txt.gotmpl
bundles/redhat7.9/repo-templates/kubernetes.repo.gotmpl
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go

feat: Create bundle for RHEL 7.9

---

.github/workflows/release-kib.yaml

fix: kib release

---

ansible/group_vars/all/defaults.yaml
ansible/group_vars/all/system.yaml
ansible/roles/packages/tasks/debian.yaml
ansible/roles/repo/tasks/debian.yaml
images/ami/ubuntu-2004.yaml

Backports of https://github.com/mesosphere/konvoy-image-builder/pull/943 and https://github.com/mesosphere/konvoy-image-builder/pull/996 to fix Ubuntu builds.
```release-note
```

[release-2.2] fix: ubuntu builds

---

.github/workflows/release-kib.yaml

****What** problem does this PR solve?**:
```release-note
```

fix: release tooling 

---

.github/workflows/release-kib.yaml

ci: fixes cappp bump

---

.github/workflows/release-kib.yaml

Run failed in https://github.com/mesosphere/konvoy-image-builder/actions/runs/8253431630
```release-note
```

fix: release workflow

---

.github/workflows/release-kib.yaml
hack/version-diff.sh

This should hopefully fix the errors with creating bump PRs https://github.com/mesosphere/cluster-api-provider-preprovisioned/pull/275
```release-note
```

fix: attempts to fix the bump again

---

ansible/group_vars/all/defaults.yaml

stacks on top of #1072 bumps the nvidia driver to the new LTSB https://docs.nvidia.com/datacenter/tesla/drivers/index.html 
```release-note
bumps nvidia gpu driver to 535 series
```

feat: bumps nvidia driver to new LTSB

---

ansible/group_vars/all/defaults.yaml
ansible/group_vars/all/system.yaml
ansible/roles/repo/tasks/debian.yaml

Fixes part (v2.4.x) of https://jira.nutanix.com/browse/D2IQ-100775
* https://jira.nutanix.com/browse/D2IQ-100775
```release-note
```

fix: use pkgs.k8s.io deb repo for k8s 1.24

---

.golangci.yml
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
cmd/konvoy-image-wrapper/cmd/wrapper.go
cmd/konvoy-image/cmd/aws.go
cmd/konvoy-image/cmd/azure.go
cmd/konvoy-image/cmd/build.go
cmd/konvoy-image/cmd/gcp.go
cmd/konvoy-image/cmd/generate.go
cmd/konvoy-image/cmd/provision.go
cmd/konvoy-image/cmd/vsphere.go
pkg/app/utils.go
pkg/logging/logger.go

Cherry-pick of https://github.com/mesosphere/konvoy-image-builder/pull/1075
```release-note
```

fix(release-2.9): linter workflow due to golangci-lint in CI (#1075)

---

.golangci.yml
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
cmd/konvoy-image-wrapper/cmd/wrapper.go
cmd/konvoy-image/cmd/aws.go
cmd/konvoy-image/cmd/azure.go
cmd/konvoy-image/cmd/build.go
cmd/konvoy-image/cmd/gcp.go
cmd/konvoy-image/cmd/generate.go
cmd/konvoy-image/cmd/provision.go
cmd/konvoy-image/cmd/vsphere.go
pkg/app/utils.go
pkg/logging/logger.go

cherry-pick #1075 
```release-note
```

fix(release-2.9): linter workflow due to golangci-lint in CI

---

ansible/roles/repo/tasks/redhat.yaml

Cherry-pick of https://github.com/mesosphere/konvoy-image-builder/pull/1081
* fix: clean yum cache after adding repos
* fix: clean cache for rhel/centos 7 only
```release-note
```

fix: clean yum cache after adding repos  (#1081)

---

ansible/group_vars/all/defaults.yaml
bundles/ubuntu20.04/bundle.sh.gotmpl
bundles/ubuntu20.04/packages.txt.gotmpl
images/common.yaml

Update to the latest version of Kubernetes.
This also includes the [changes needed](https://github.com/mesosphere/dkp-release/pull/123) for [the new dynamic credential provider](https://github.com/mesosphere/konvoy-image-builder/pull/1084).
```release-note
```

feat: update Kubernetes to v1.29.5

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/gcp-e2e.yaml
.github/workflows/release-ami.yaml
.github/workflows/release-azure.yaml
.github/workflows/release-gcp-template.yaml
.github/workflows/release-vcd-template.yaml
.github/workflows/release-vsphere-template.yaml
.github/workflows/vsphere-e2e.yaml

I noticed the e2e tests sometimes die with "The operation was canceled.", trying larger (medium) sized runners.
```release-note
```

ci: run tests on medium runners

---

.github/workflows/release-vsphere-template.yaml

rhel 8.8 fips tests needed https://github.com/mesosphere/konvoy2/pull/2839
```release-note
```

ci: modifies vsphere release job

---

.github/workflows/release-vsphere-template.yaml

Builds a template [needed for Konvoy e2e tests](https://github.com/mesosphere/konvoy2/blob/300aca62c948e628e58056659f26969e9bf969fe/.github/workflows/daily_e2e_tests.yaml#L156-L157).
```release-note
```

build: build vSphere RHEL 8.6 FIPS template

---

ansible/group_vars/all/defaults.yaml

Updates to latest Containerd patch release https://github.com/containerd/containerd/releases/tag/v1.6.33
* https://jira.nutanix.com/browse/NCN-100614
```release-note
```

fix: bump Containerd patch release 1.6.33

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Updates to latest Kubernetes patch release https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#changelog-since-v1295
* https://jira.nutanix.com/browse/NCN-100488
```release-note
```

fix: bump Kubernetes patch release 1.29.6

---

.github/workflows/podman-aws-e2e.yaml
cmd/konvoy-image-wrapper/image/image.go

Backport of #1116.
* https://jira.nutanix.com/browse/NCN-101343
```release-note
```

fix: Make image load compatible with podman 4.x 

---

.github/workflows/podman-aws-e2e.yaml
cmd/konvoy-image-wrapper/image/image.go

Backport of #1116 
* https://jira.nutanix.com/browse/NCN-101343
```release-note
```

fix: Make image load compatible with podman

---

ansible/roles/containerd/tasks/redhat.yaml
ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo

https://jira.nutanix.com/browse/NCN-101437
```release-note
```

fix: adds oracle 7 repos

---

pkg/packer/manifests/aws/packer.pkr.hcl

Removes snapshot groups from being shared.
```release-note
```

fix: remove snapshot groups

---

Dockerfile.devkit

Downgrade the Packer version to a version that fixes critical CVEs.
Image built from https://github.com/mesosphere/packer/commits/release/v1.9.5-nkp.1/
* https://jira.nutanix.com/browse/NCN-101657
```release-note
```

fix: downgrade packer version

---

bundles/redhat8.6/bundle.sh.gotmpl
bundles/redhat8.6/packages.txt.gotmpl
bundles/redhat8.8/bundle.sh.gotmpl
bundles/redhat8.8/packages.txt.gotmpl
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
magefile.go

Allows users to optionally disable using EUS repos for redhat 8.6 and 8.8
Also sets owner permissions to solve : https://jira.nutanix.com/browse/NCN-101832
```release-note
```

feat: allows setting EUS repos with a flag

---

Dockerfile
Dockerfile.devkit
ansible/roles/providers/tasks/aws.yml
bundles/redhat8.6/bundle.sh.gotmpl
bundles/redhat8.8/bundle.sh.gotmpl
bundles/rocky9.1/bundle.sh.gotmpl

bundles ssm rpm in the docker file to directly copy inside vm 
https://jira.nutanix.com/browse/NCN-101868
```release-note
```

fix: adds ssm from docker image

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

https://jira.nutanix.com/browse/NCN-101949
```release-note
```

feat: bumps cni to 1.3.0

---

ansible/roles/packages/tasks/redhat.yaml

fix: removes duplicate key

---

.github/workflows/release-kib.yaml
.goreleaser-podman-e2e.yml
.goreleaser.yml

Adds macos binary notarization.
* https://jira.nutanix.com/browse/NCN-102094
```release-note
```

fix: add macos binary notarization

---

magefile.go

Backport of #912 
Prior to this change, we used a CentOS 7.9-based container to download PIP packages. With CentOS 7.9 repositories no longer available, that is not possible.
This is needed to build images; specifically, vSphere images for Konvoy e2e tests.
```release-note
```

[release-2.5] chore: download pip packages from downloads.d2iq.com

---

pkg/packer/manifests/aws/packer.pkr.hcl

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1124
* https://jira.nutanix.com/browse/NCN-101592
```release-note
```

[release-2.8] fix: remove snapshot groups (#1124)

---

Makefile
ansible/group_vars/all/defaults.yaml
images/common.yaml

Update kubernetes version to 1.29.9
* https://jira.nutanix.com/browse/NCN-103029
```release-note
```

fix: update kubernetes version to 1.29.9

---

Makefile
ansible/group_vars/all/defaults.yaml
images/common.yaml

* fix: update kubernetes version to 1.29.9
* fix: rebuild devkit image if kubernetes version changes
```release-note
```

fix(release-2.14): update kubernetes version to 1.29.9 (#1195)

---

ansible/group_vars/all/system.yaml
ansible/roles/gpu/tasks/nvidia-gpu-RHEL.yaml
ansible/roles/repo/tasks/redhat.yaml

fix: remove appstream code as its not needed

---

Dockerfile.devkit

Using latest patch Go version to fix any CVEs. 
```release-note
```

build: update Go builder version to v1.19.13

---

Dockerfile.devkit
pkg/packer/manifests/aws/packer.pkr.hcl
pkg/packer/manifests/azure/packer.pkr.hcl
pkg/packer/manifests/gcp/packer.pkr.hcl
pkg/packer/manifests/vsphere/packer.pkr.hcl

See https://github.com/mesosphere/packer-plugin-goss/releases/tag/v3.3.0
Using Go 1.22 to build the plugin.
Fixes most CVEs in the plugin.
```
trivy fs .
2024-10-22T13:26:00-07:00	INFO	[vuln] Vulnerability scanning is enabled
2024-10-22T13:26:00-07:00	INFO	[secret] Secret scanning is enabled
2024-10-22T13:26:00-07:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-10-22T13:26:00-07:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.55/docs/scanner/secret#recommendation for faster secret detection
2024-10-22T13:26:02-07:00	INFO	Number of language-specific files	num=1
2024-10-22T13:26:02-07:00	INFO	[gomod] Detecting vulnerabilities...
go.mod (gomod)
Total: 7 (UNKNOWN: 0, LOW: 0, …
```

fix: update goss Packer plugin

---

.github/workflows/podman-aws-e2e.yaml

fix: tests for podman

---

.github/workflows/release-gcp-template.yaml

ci: use new GCP credentials for release GCP images workflow

---

goss/oracle/kernel-params.yaml
goss/rhel/kernel-params.yaml
goss/ubuntu/kernel-params.yaml

[backport 2.13] fix: removes ipv6 disabled check from goss (#1235)

---

goss/oracle/kernel-params.yaml
goss/rhel/kernel-params.yaml
goss/ubuntu/kernel-params.yaml

[backport 2.9] fix: removes ipv6 disabled check from goss

---

bundles/redhat8.10/packages.txt.gotmpl
bundles/redhat8.8/packages.txt.gotmpl

fix: Nvidia kernel versions in air-gapped bundle

---

requirements-devkit.txt

Fixes devkit build error [here](https://github.com/mesosphere/konvoy-image-builder/actions/runs/12401533880/job/34621110087?pr=1239#step:8:3743).
```release-note
```

build: update azure-cli version

---

.github/workflows/azure-e2e.yaml
.github/workflows/release-azure.yaml
images/azure/ubuntu-2204.yaml

For Azure, add Ubuntu 22.04 KIB e2e test for Azure
https://jira.nutanix.com/browse/NCN-104800

feat: Azure add support for ubuntu-22.04

---

.github/workflows/lint.yml
ansible/roles/providers/files/etc/cloud/cloud.cfg.d/90_dpkg.cfg
ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py
ansible/roles/providers/tasks/aws.yml
ansible/roles/providers/tasks/main.yml

feat: adds custom datasource for ubuntu 22.04

---

bundles/redhat8.10/packages.txt.gotmpl

[stacked] fix: updates kernel headers for rhel 8.10 on AWS

---

ansible/group_vars/all/defaults.yaml
bundles/redhat8.10/packages.txt.gotmpl

* https://jira.nutanix.com/browse/NCN-105616
```release-note
```

feat: bumps nvidia driver

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

Kubernetes patch version (1.30.10)bump
https://jira.nutanix.com/browse/NCN-105973
```release-note
```

[release-2.18] feat(k8s): Bump to latest patch 1.30.10

---

bundles/redhat8.10/packages.txt.gotmpl
bundles/redhat8.8/packages.txt.gotmpl

Fixes Nvidia tests.
```release-note
```

[release-2.18] fix: kernel versions for Nvidia

---

bundles/redhat8.10/packages.txt.gotmpl
bundles/redhat8.8/packages.txt.gotmpl

fix Nvidia driver
https://jira.nutanix.com/browse/NCN-105350

feat: nvidia kernel headers fix

---

.github/workflows/podman-aws-e2e.yaml
Dockerfile
Dockerfile.devkit
Makefile
ansible/group_vars/all/defaults.yaml
ansible/roles/images/tasks/main.yaml
ansible/roles/images/tasks/upload.yaml
ansible/roles/offline/tasks/upload.yaml
bundles/redhat8.10/packages.txt.gotmpl
bundles/redhat8.8/packages.txt.gotmpl
hack/download-artifacts.sh
magefile.go
overrides/offline-fips.yaml
overrides/offline.yaml

Cherry-pick https://github.com/mesosphere/konvoy-image-builder/pull/1270
```release-note
```

fix(release-2.22): download kubernetes images in the KIB container  (#1270)

---

.github/workflows/podman-aws-e2e.yaml
Dockerfile
Dockerfile.devkit
Makefile
ansible/group_vars/all/defaults.yaml
ansible/roles/images/tasks/main.yaml
ansible/roles/images/tasks/upload.yaml
ansible/roles/offline/tasks/upload.yaml
bundles/redhat8.10/packages.txt.gotmpl
hack/download-artifacts.sh
magefile.go
overrides/offline-fips.yaml
overrides/offline.yaml

Cherry-pick https://github.com/mesosphere/konvoy-image-builder/pull/1270
```release-note
```

feat(release-2.18): download kubernetes images in the KIB container  (#1270)

---

ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py

This fixes the linter error. While looking at this, I also noticed that the second log message was using the wrong variable.
```release-note
```

fix: custom cloudinit script

---

.github/workflows/release-kib.yaml

bump GHA runner to large
```release-note
```

ci: bump GHA runner to large for release workflow

---

ansible/group_vars/all/defaults.yaml
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
hack/download-artifacts.sh
images/common.yaml

Bump to latest Kubernetes release in KIB
(https://jira.nutanix.com/browse/NCN-105350)

feat: bump the Kubernetes version to v1.32.3

---

.golangci.yml

Followed the steps in https://golangci-lint.run/product/migration-guide/
```release-note
```

build: update golangci linter config

---

.github/workflows/aws-e2e.yaml
.github/workflows/release-ami.yaml
images/ami/rocky-95.yaml
magefile.go

Adds building Rocky 9.5 support for AWS.
* https://jira.nutanix.com/browse/NCN-107045
Since we do not yet have the new bundle command, the air-gapped tests will fail, but we will still get a good signal from the basic config.
The air-gapped paths will be tested with the bundle PR.
```release-note
```

feat: support building Rocky 9.5 AWS images

---

.golangci.yml

Backport of https://github.com/mesosphere/konvoy-image-builder/pull/1285
Followed the steps in https://golangci-lint.run/product/migration-guide/
```release-note
```

build(release-2.18): update golangci linter config

---

.github/workflows/release-vsphere-template.yaml
.github/workflows/vsphere-e2e.yaml
test/infra/vsphere/main.tf
test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
test/infra/vsphere/packer-vsphere-basic.yaml.tmpl
test/infra/vsphere/variables.tf

Backport #1270
* ci: run vsphere tests on nkp vcenter
* ci: build vsphere in airgapped network
```release-note
```

ci(release-2.22): run vsphere e2e tests on nkp vcenter (#1289)

---

.github/workflows/aws-e2e.yaml
.github/workflows/azure-e2e.yaml
.github/workflows/build-devkit-image.yaml
.github/workflows/build.yml
.github/workflows/gcp-e2e.yaml
.github/workflows/release-ami.yaml
.github/workflows/release-azure.yaml
.github/workflows/release-gcp-template.yaml
.github/workflows/release-kib.yaml
.github/workflows/scorecards.yml
.github/workflows/sync-cli-docs.yaml
.github/workflows/unit-test.yml
.vscode/settings.json

Move all the GHA workflows to use the runners on nutanix infrasturcture
* https://jira.nutanix.com/browse/NCN-103700
```release-note
```

ci: move all github action workflows to use nutanix runners

---

bundles/redhat8.10/packages.txt.gotmpl

Bumping kernel headers for nvidia for rhel 8.10
https://jira.nutanix.com/browse/NCN-107452
n/a
n/a

fix(release-2.23): bump nvidia kernel headers for RHEL 8.10

---

ansible/group_vars/all/defaults.yaml
images/common.yaml

bump  kubernetes patch version (1.31.9)
release-2.14.1
https://jira.nutanix.com/browse/NCN-107586
```release-note
```

[release-2.22] feat(k8s): Bump to latest patch 1.31.9

---

.vscode/settings.json
ansible/group_vars/all/defaults.yaml
images/common.yaml

bump Kubernetes to 1.33.1
https://jira.nutanix.com/browse/NCN-105350

feat: Bump K8s to 1.33.1

---

.github/workflows/aws-e2e.yaml
bundles/rocky9.6/bundle.sh.gotmpl
bundles/rocky9.6/packages.txt.gotmpl
cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
images/ami/rocky-96.yaml
magefile.go

Adds rocky 9.6 support for AWS
```release-note
```

feat: adds rocky 9.6 build for aws

---

ansible/group_vars/all/defaults.yaml
bundles/redhat8.10/packages.txt.gotmpl
images/common.yaml

bump kubernetes version to v1.33.2 (update the latest 1.33 patch)
https://jira.nutanix.com/browse/NCN-108169
```release-note
```

feat: bump kubernetes version to v1.33.2 

---

ansible/roles/packages/tasks/debian.yaml
ansible/roles/repo/tasks/debian-offline.yaml

Takes the cache updates from #1326 and adds them to main 
```release-note
```

fix: change update cache logic for debian
